BoltApp/bolt-magento1

- app/code/community/Bolt/Boltpay/Helper/Api.php
We do not want the code to completely fail if there is a problem with a single shipping option.
Reasoning:
The idea of our plugin is to increase conversions.  It is not to make sure that FedEx, or ShippingHQ, or UPS, or whatever plugin is working.  There can be any number of reasons why one maybe down, like internet problems, or strict address validation for a particular region, whereas other shipping methods will not fail.
If any given shipping method fails for whatever reason, it is good to note it, but we must present the customer with all available shipping options so that they can check out of Bolt successfully and increase our conversion rates.
When making a decision like this, it may be good to consider what the underlying system would do.  In this instance, we can ask ourselves, …
> Reducing exception from fatal to notification on shipping method problem

- app/code/community/Bolt/Boltpay/Helper/Api.php
- app/code/community/Bolt/Boltpay/Helper/Bugsnag.php
- app/code/community/Bolt/Boltpay/Model/Api2/Order/Rest/Admin/V1.php
- app/code/community/Bolt/Boltpay/Model/Payment.php
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
- app/code/community/Bolt/Boltpay/controllers/OrderController.php
I think there are other code that makes http request. can you update other places too?
@daisy1754 most of BOLT request call from using API helper Transmit method, 
all other http request data already added to Bugsnag Breadcrumb
Ex. bolt hook request we added reference and quote id in Breadcrumb
> Renaming addMetaData to addBreadcrumb

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- app/code/community/Bolt/Boltpay/Helper/Api.php
when processing Magento order creation in API,  getCustomerIsGuest is false even the customer isnot logged in, so we need to explicitly set it to false for guest. to avoid misjudgement in thrid-party modules
> Explicitly set quote belong to guest if customer id does not exist

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
This is background for this PR
When I run test on merchant site, I found a strange issue. This merchant site has some customer groups that would have a discount (actually it is a customer group price) on the products of some categories, then I try to checkout as a logged customer in such a customer group, two products in the cart, one is configurable product and another is simple product. and on the shipping method tab, the tax is always wrong. and I found that the price of configurable product would be changed to its original price while the simple product keep correct during quote->collectTotals() process especially when address->collectTotals() every time, that's why the tax is wrong. 
and I dig into it
1. when address->collectTotals() it would collect each total object, and for this …
> Correct the price and tax calculation for group customer

- app/code/community/Bolt/Boltpay/Helper/Api.php
- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
Here is the new branch and pull request for overriding shipping and tax estimate when prefetch makes request with invalid zip code.
See also: https://github.com/BoltApp/bolt-magento1/pull/55
> Bypass getShippingAndTaxEstimate if post code is invalid.

- app/code/community/Bolt/Boltpay/Helper/Data.php
- app/code/community/Bolt/Boltpay/etc/config.xml
- app/code/community/Bolt/Boltpay/etc/system.xml
- app/code/community/Bolt/Boltpay/sql/bolt_boltpay_setup/upgrade-1.1.4-1.1.4.9.php
- app/design/frontend/base/default/template/boltpay/track.phtml
Currently, plugin stores "publishable key" as encrypted data but there is no need (it is publishable). Let's not encrypt.
> Make publishable key unencrypted

- app/code/community/Bolt/Boltpay/Model/Observer.php
- app/code/community/Bolt/Boltpay/etc/config.xml
Currently, for logged in users, the shopping cart is not being emptied after successful orders.
This commit makes sure that the cart is emptied.
> adds clearing of cart in observer before displaying success page

- app/code/community/Bolt/Boltpay/Helper/Api.php
The error checks here for an empty quote are outdated, with the first one being very off as an empty quote will not have a reserved order id.
If the immutable quote is empty, then this is an unexpected problem that implies the quote was somehow deleted.  We currently do not delete these cloned quotes.
> Updated missing quote error checks from bad merge

- app/code/community/Bolt/Boltpay/Helper/Api.php
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
- app/code/community/Bolt/Boltpay/controllers/OrderController.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/ApiTest.php
Logic for removing display id from Bolt order creation and adding it to the first successful hook call per the spec defined at https://docs.bolt.com/v1/docs/hook-integration-1 under **Hook Responses**
> Reset in use increment id complete solution

- app/code/community/Bolt/Boltpay/Helper/Api.php
- app/code/community/Bolt/Boltpay/etc/config.xml
- app/design/frontend/base/default/template/boltpay/track.phtml
- create_release.sh
Several times we have observed that the reserved order id (increment id) can be used even though a quote has "reserved" it.  This is also implied as an expectation in core Magento code in class `Mage_Sales_Model_Quote`
```
/**
* Generate new increment order id and associate it with current quote
*
* @return Mage_Sales_Model_Quote
*/
public function reserveOrderId()
{
if (!$this->getReservedOrderId()) {
$this->setReservedOrderId($this->_getResource()->getReservedOrderId($this));
} else {
//checking if reserved order id was already used for some order
//if yes reserving new one if not using old one
if ($this->_getResource()->isOrderIncrementIdUsed($this->getReservedOrderId())) {
$this->setReservedOrderId($this->_getResource()->getReservedOrderId($this));
}
}
return $this;
}
```
This fix is …
> Generate new increment id if detected as already in use

- app/code/community/Bolt/Boltpay/Helper/Api.php
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
- app/code/community/Bolt/Boltpay/controllers/OrderController.php
- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/ApiTest.php
https://app.asana.com/0/544708310157130/752340529245956
Using the parent ID as the order_reference in Bolt order creation allows for the Bolt backend to provide for integrity constraints, enforcing a single order creation per session.
This addresses the problem of double billing the customer for the same order (i.e. one order created in Magento, while two transactions created at Bolt.)
This has already been implemented in Magento 2
> Parent id as order reference to enable bolt side duplicate order detection

- js/boltpay/admin_order.js
Context:
Usually, all elements are pre-loaded on the first call to the admin create page, and all views are shifted via AJAX.  Though initially Indique followed this same pattern, after they altered their core code, certain elements were no longer pre-loaded.  Because, in Javascript, it is generally a good practice to check for an objects existence before attempting to access its data members, including this check in our plugin strengthens the code base.
> Checks for elements before trying to access their data members

- app/code/community/Bolt/Boltpay/Helper/Data.php
If there is other 3rd-party also extend the same modal, it would cause error, so it should be clarified
> Get the right modal object

- app/code/community/Bolt/Boltpay/controllers/OrderController.php
Comments added to make extra sure that developers do not make the mistake of assuming that equivalent functionality is guaranteed by similar function names in this code.
> Clarification comments on similarly named functions

- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
Found this bug today on StriVectin. Our billing address region_id is always null.
> Added billing address region_id to billing address. Currently it is null

- app/code/community/Bolt/Boltpay/Helper/Api.php
item price can be factional with discount. Previous logic can cause off-by-one error.
Example:
```
round(3.9777 * 100 * 4) => 1591
round(3.9777 * 100) * 4 => 1592
```
> Fix off-by-one rounding issue for item total_amount

- app/code/community/Bolt/Boltpay/Helper/Api.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/ApiTest.php
Add some adhoc rules to account for common store settings that caused non-optimal UI. 
- Remove 'Shipping Table Rates' prefix
- Remove 'United Parcel Service' prefix if title already contains 'UPS'
- Remove carrier name if the same text is included in method title
> Add logic to tweak shipping label so it looks nicer

- app/code/community/Bolt/Boltpay/Helper/Api.php
Magento issues a standard event `checkout_submit_all_after` after order creation that we currently do not dispatch.  
We should dispatch this event so that plugins that rely on it can function properly
> Dispatch order save after events

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- app/code/community/Bolt/Boltpay/controllers/OrderController.php
- app/code/community/Bolt/Boltpay/etc/config.xml
- app/design/frontend/base/default/template/boltpay/replace_firecheckout.phtml
- tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
- tests/unit/testsuite/Bolt/Boltpay/TestHelper.php
This is a revision of the Firecheckout code that removes reliance on hard-coded classes, bolt classes that will no longer be supported in the future, and implements loading the order token via a Promise.
> Firecheckout remove hard-coded selectors and implement via promise

- app/code/community/Bolt/Boltpay/controllers/ApiController.php
Uses display_id to look up order once it has been confirmed to be accurate.  
If not confirmed, the display_id will have a "|" and will never find an order.  Then, we use the quoteId.
If there is no "|", then we know the the display_id has been confirmed as accurate and we use it.  In this way, even if the quote has been deleted, the webhooks will still succeed as they no longer need the quote, only the order.
This is the code that is in production for one client that solved their problem.
> Solves the parent quote missing issue

- app/code/community/Bolt/Boltpay/Helper/Api.php
In Magento 1, we've had some long standing code that checks for all the required shipping fields to exist.  If any are missing, it removes the address and the shipping method in entirety in order to pass Bolt validation.
https://github.com/BoltApp/bolt-magento1/blob/develop/app/code/community/Bolt/Boltpay/Helper/Api.php#L744-L753
https://github.com/BoltApp/bolt-magento1/blob/develop/app/code/community/Bolt/Boltpay/Helper/Api.php#L867-L872
I don't believe that this sort of code exist in any other plugins, and I believe that by including it, we create the scenario for orders to get placed on Bolt minus shipping address and shipping method info.  In such a case, it is much better to fail early rather than later and allow the BoltCheckout to indicate the missing field problem to the customer. …
> Keep shipping data even if a required field in option address is missing

- app/code/community/Bolt/Boltpay/Helper/Api.php
provides a fallback to city if the region is omitted in non-US, non-CA countries to comply with Bolt's requirement for this field which Magento sees as optional for most countries in the world.
> provides region fallback to city for shipping address

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- app/code/community/Bolt/Boltpay/Helper/Api.php
- tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
- tests/unit/testsuite/Bolt/Boltpay/TestHelper.php
Fixes 
1.) The json cart creation error always taking precedence over all other custom and contextual checks
2.) Merchant-side plugin defined errors also being included. (Before only Bolt-server side errors were displayed.
3.) Fixes "Mage registry key "api_error" already exists" error that can be found in bugsnag
> Corrects BoltCheckout error check logic

- app/code/community/Bolt/Boltpay/Model/Cron.php
- app/code/community/Bolt/Boltpay/etc/config.xml
/**
* After an immutable quote has existed for a week or more, we remove it from the system.
* At this point, only the order object is relevant for converted orders and any immutable
* quote that was to be converted will have been handled well before this time.
*
* As an artifact, we leave the parent quotes and delegate cleanup responsibility of these to
* the merchants.
*/
Addresses https://github.com/BoltApp/bolt-magento1/issues/173
> Cleans up old expired immutable quotes

- app/code/community/Bolt/Boltpay/Model/Admin/Form/Color.php
Proposal to allow empty string as a valid value to fall back to Bolt defaults.
If not, once a color is set, it can not be unset to allow for Bolt defined defaults.
> Allow for empty string to be set.

- app/design/frontend/base/default/template/boltpay/replace_firecheckout.phtml
Setting `cssText` to empty string was removing `--bolt-primary-action-color` attribute which triggers the problem.
`cssText` was previously needed to set the `!important` directive, however, it seems the internal Bolt produced CSS was revised to not force this, and therefore, we can use `display` without the `!important` directive.
> Fixes disappearing Bolt Button in firecheckout

- app/design/frontend/base/default/template/boltpay/replace.phtml
Payment-only merchant doesn't want replace.js is included in cart page
> Include replace.js only when publishable key is defined

- app/code/community/Bolt/Boltpay/controllers/OrderController.php
lockcartAction was a non-adopted precursor to immutable/cloned quotes and is not used nor should it be exposed.
It is being removed to reduce clutter in the controller which is anticipated to be populated with methods for API initiated order updates.
> removes unused endpoint

- app/code/community/Bolt/Boltpay/Model/Quote.php
Removes informational comment concerning Bolt required address fields.
This can be optionally applied to unblock Pull Request https://github.com/BoltApp/bolt-magento1/pull/209
> Removed informational comment

- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
I found a bug when testing on Golf land. Parent quote is being removed when estimating the shipping with login customer.
When setting the customer to session, it will get a current customer quote which is parent quote and then merges the quote that being on the session and then remove the parent quote.
> Moved the logic to set quote_id to session after setting customer to session

- app/code/community/Bolt/Boltpay/Helper/Data.php
We need to specify the key of validator class in salesrule/validator, because core magento uses a property of this class to calculate the rounding.
Basically every time, we collect the total, we need to reset it to empty or else a rounding error occurs.
> Get correct singleton object

- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
- app/code/community/Bolt/Boltpay/Model/Order/Detail.php
- app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
Fixed the issue with simple product sku not being sent to Bolt when associated with a configurable parent sku.
> Simple product sku is saved incorrectly on Bolt

- app/code/community/Bolt/Boltpay/Model/Observer.php
- app/code/community/Bolt/Boltpay/Model/Payment.php
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
When implementing multiple capture for Magento 1 Bolt set the transaction status to complete after partial capture. When implementing multiple capture for Magento 2, I realized the transaction status should be authorized in M1 due to new logic. Created this task to fix the M1 version.
> Updated multiple capture

- tests/scripts/run_phpunit_tests.sh
With the version of phpunit we use, testdox cannot show error details when test fails
> Remove testdox from CI phpunit

- .gitignore
- composer.json
- tools/pre-commit
- tools/setup.sh
Here is my first pass at githooks to check linting and style. After pulling this branch, all you need to do is a `composer install` and you're set up. You may need to enter magento credentials the first time you `composer install` (to fetch the `MEQP1` standard).
When you commit, the following happen in order:
1. A basic lint is performed using `php -l`. If this fails, your commit is aborted.
2. A style check against `MEQP1` is performed using `phpcs`. This checks for both errors and warnings.
3. You are given an (optional) prompt to automatically fix warnings and errors.
4. `phpcs` is run again, only checking errors. If no errors are present, your commit goes through - if errors still exist, your commit is aborted.
Please find some screenshots attached with examples:
**PHP Lint fails, …
> Add pre-commit hook for checking PHP Lint and MEQP1 style checking

- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
Sum of discounts sent to Bolt was not accounted for as a positive number.  This revises Bolt totals calculations treating discounts as a positive number like it is done on the Bolt server.
> Use discount as positive since Bolt uses positive

- app/code/community/Bolt/Boltpay/Helper/Data.php
https://app.asana.com/0/544708310157130/1108368077993428
A generic filter event is need for filtering strings, arrays, objects, etc. such as javascript, product descriptions, prices, address data, etc.
> Add generic event filter construct

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
- tests/unit/testsuite/Bolt/Boltpay/TestHelper.php
https://app.asana.com/0/544708310157130/1108757786846726
Since BoltCheckout.configure now returns an object with an "open" method and "hasBoltButton" boolean, this object should be made available to the global browser scope
As an example, this will allow for code such as:
```
var customerIsLoggedIn = <?= ($this->customerIsLoggedIn()) ? 'true' : 'false';>;
var wasLoggedInByBolt = <?= ($this->wasBoltInitiatedLogin()) ? 'true' : 'false';>;
if (customerIsLoggedIn && wasLoggedInByBolt && BoltModal.hasBoltButton) {
BoltModal.open();  // automatically open the Bolt modal
} else if (!customerIsLoggedIn) {
doBoltInitiatedCustomerLogin();  // will refresh page
}
```
> Exposes javascript Bolt Modal object to be available in window context

- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
If $quote->getAppliedRuleIds() returns a string value, cast to an array to avoid foreach error on string.
> Cast to Array if String Value forEach

- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
Explicitly clear the headers before we send the headers to ensure any native or third-party modules have not already set the header.
> add clearHeaders before setHeader

- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
https://app.asana.com/0/544708310157130/1108910545116701
This refactors so that adding a shipping method to the quote always goes down the same path to assure discounts and rules are always recalculated.  This DRYs out the codebase
This also adds distinction between the event for adding a shipping rate to the quote for general purposes like shipping and tax estimates and add the shipping rate in the process of order creation.
> Add call to singular method for setting shipping method.

- app/code/community/Bolt/Boltpay/Model/Order.php
Set the billing name from the transaction object explicitly to prevent issues like https://app.asana.com/0/941895179897714/1107491074225023/f
Images are in Asana of the problem being fixed.
> Populate billing name

- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
https://app.asana.com/0/544708310157130/928424426880722
Rather than trying to programmatically solve very specific shipping address failure cases, we can take the more generic approach of reporting the error back to the customer so that they can fix the problem themselves at checkout time just as we already do for P.O. Box errors.
> Reports address errors to customer so that they can be corrected at checkout time

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
https://app.asana.com/0/941895179897714/1110284468674223/f
The config is an `Extra config` boolean value called `cloneOnClick`.  
Example usage to enable cloning on Bolt button click:
In the Magento Admin `System -> Configuration -> Payment Methods -> Bolt Pay -> Extra Config`
```
{
"boltPrimaryColor":"#fff000",
"hintsTransform":
"
function(hints){
hints.prefill = 
{\"email\":\"leon@bolt.com\"};
return hints;
}
",
"cloneOnClick": true
}
```
> Allows merchant to specify quote cloning/Bolt order creation on Bolt button click

- app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
https://app.asana.com/0/inbox/544708310157128/1110257233649801/1110933955640367
> fixes php7 not json decoding null by using empty array instead

- .circleci/config.yml
Integration test runs based on the latest content of develop branch. This PR restrict integration test run on develop/master/circleci. (circleci branch is used to test tweaking config change)
> Only run integration test on relevant branches

- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
- 403 (forbidden) is not appropriate. 422 (unprocessable entity) seems better 
- Bolt has monitoring around 403 to detect bad CDN config - in the past cloudflare rejected bolt's request - so let's not use 403 in app layer
> Use status code 422 for shipping controller error

- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
- app/code/community/Bolt/Boltpay/Model/Coupon.php
- tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/BoltOrderTest.php
Bolt order creation is improved by
- bugfix: Uses proper id of cart item which is critical for cart item change inspection
- enhancement: Adding coupon reference to the Bolt order
- adding session/quote context information when adding discounts to the order
Style improved by
- using conventional boolean naming conventions 
- adding better spacing and indentation
Test improved by
- being consistent in using Quote's `getAllVisibleItems` method to generate bolt cart
> mPR02 - Bolt order creation bugfixes, improved internal docs, naming, and formatting

- app/code/community/Bolt/Boltpay/Helper/GeneralTrait.php
This is a subtle bugfix for fully clearing totals when required.
Details: 
https://stackoverflow.com/questions/5671787/unset-shipping-and-recalculate-totals-in-magento
> mPR.04 - On collect totals with clear totals true, cached shipping items must be removed to fully clear price

- app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
Correctly add coupon in shipping calculations and events at all key shipping and tax moments to remove the need to override Bolt core methods
> mPR.06 - Include coupon in shipping and tax estimate 

- app/design/frontend/base/default/template/boltpay/replace.phtml
Context:
Bolt button disappears from mini cart when quantity is updated (desktop and mobile)
https://app.asana.com/0/inbox/544708310157128/1122886631659761/1123291135314664
> Re-renders button in mini-cart after it is ajax reloaded

- app/code/community/Bolt/Boltpay/Model/Observer.php
- app/code/community/Bolt/Boltpay/etc/config.xml
Many plugins change the status of orders.  We do not want to allow this for Bolt pre-auth orders statuses so we restrict changes from that state to only Bolt webhooks.
https://app.asana.com/0/1118494470563243/1123688922955292
> mPR.10 - Restricts changing preauth status to only Bolt webhooks

- app/code/community/Bolt/Boltpay/Model/Observer.php
- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
- app/code/community/Bolt/Boltpay/etc/config.xml
When Bolt cancels a pre-auth pending order, we must 
1.) Release all resources like inventory.  This is done via cancel
2.) Remove the order.  This is done via delete
3.) expire the cache to trigger new Bolt order creation, otherwise the expired token will continue to be used by the Magento plugin.  This handles the expiration.
https://app.asana.com/0/1118494470563243/1123688922955296
> mPR.11 - Pre-auth order canceling

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- app/code/community/Bolt/Boltpay/Helper/ConfigTrait.php
- app/code/community/Bolt/Boltpay/etc/system.xml
- tests/unit/testsuite/Bolt/Boltpay/Helper/ConfigTraitTest.php
Allowed custom route for Bolt button.
This change allows showing Bolt button if the checkout/cart (or other default pages which we use with Block/Checkout/Bolt.php) page was rewritten.
> Allowed custom route for Bolt button.

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
https://app.asana.com/0/941895179897714/1121581354248363/f
Quick fix to ignore dummy data the Apple Pay prefills. This occurs when someone clicks on Apple Pay, then cancels out of the apple pay order and uses Bolt Checkout. Many users just keep the dummy data there. Example attached below.
> Ignore apple pay prefill

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
Current code will generate errors in strict environments.   We suppress notices for undefined array indexes to address the problem.
> Fixes error generated when Apple Pay prefill values are not defined

- app/code/community/Bolt/Boltpay/Controller/Traits/WebHookTrait.php
- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
https://app.asana.com/0/544708310157130/1119041817660804
Fetching the bolt transaction for pending hooks is not necessary and was causing the initial pending hook after a pre-auth order to always timeout.
This optimizes the pending hook by using the available display_id provided in the hook to look up the order, eliminating the need to do a fetch.  In this way, the hook now completes on time.
> optimization for pending hooks to succeed on first call

- app/code/community/Bolt/Boltpay/Model/Payment.php
The subsequent calls to the the fetch endpoint were failing.  The extra calls were not needed and we should be reusing the initial call to fetch's transaction
https://github.com/BoltApp/bolt-magento1/blob/bugfix/remove-unnecessary-calls-to-fetch-bolt-api/app/code/community/Bolt/Boltpay/controllers/ApiController.php#L57
https://github.com/BoltApp/bolt-magento1/blob/bugfix/remove-unnecessary-calls-to-fetch-bolt-api/app/code/community/Bolt/Boltpay/controllers/ApiController.php#L112
> Removes unnecessary and error generating calls to Bolt Fetch by  the first successful call

- .github/CODEOWNERS
Adding `CODEOWNERS` file to automatically request reviews.
https://github.blog/2017-07-06-introducing-code-owners/
> Add m1 codeowners

- app/code/community/Bolt/Boltpay/Model/Payment.php
The total from $boltTransaction->amount->amount reflects the refund or capture amount in those respective hooks.   When looking for the order total, instead, we must use $boltTransaction->order->cart->total_amount->amount
https://app.asana.com/0/1118494470563243/1126541145082318
> Pulls order total from the order object of the transaction

- app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
For many, many releases in 1.x and possibly 0.x we have always allowed for a price-mismatch of 1 cent due to rounding errors in discount and tax because Bolt requires these prices to be separated while Magento collectively rounds and in some cases, has a slightly different algorithm for displaying values like discount in quote estimations than what it produces in quote to order conversion.  
Complete description is at https://app.asana.com/0/544708310157130/1127097389119930
> Restore our long-standing default behavior of allowing a 1 cent price difference

- README.md
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
There will be cases where merchants override all _/checkout/onepage_ url paths which include the _/checkout/onepage/success_ url used for preauth.
In order to provide a means of not overriding the entire Onepage controller method for this point or any reason, we provide a means to write a custom url via filter.  As an example, in the case described above, we will want to replace _/**checkout**/onepage/success_ with _/**boltpay**/onepage/success_
https://app.asana.com/0/544708310157130/1127609963001801
> Allows for custom success URL

- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
For case when requestMustBeSigned = false.
The root cause of error is in Magento's store code in url.
Usually it looks like (for ajax) http://example.com/en/boltpay/shipping/prefetchEstimate/
Magento's setting(choose `Default Config` in scope view): `System > Configuration > General > Web > Add Store Code to Urls` set to Yes.
Previously in code we get data from request through `getRequestUri()`, current method get data like `/en/boltpay/shipping/prefetchEstimate/`. Instead of  `getRequestUri` i put method `getPathInfo()` which returns `/boltpay/shipping/prefetchEstimate/`
> Get path for route condition.

- app/code/community/Bolt/Boltpay/Model/Order.php
- tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
Using the native email sent methodology is preferred as it will be detected if a third party plugin sets this, whereas our existing method will not.
https://app.asana.com/0/544708310157130/1128043171296216
> Uses native Magento method for determining if order email has been sent

- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
- tests/unit/testsuite/Bolt/Boltpay/Model/ShippingAndTaxTest.php
Problem:
If the discount is changed after shipping and tax, for instance, if the Magento Admin is set to include tax as part of a percentage based discount, then pre-auth validation fails and the recorded Bolt totals will be incorrect.  Currently, this will block an order from being able to be processed.
Proposed Solution:
We have always utilized shipping tax in order to get the correct amount for total tax for similar reasons.  Now, we utilize the shipping cost estimate to include the price discount difference and disable subtotal validation in pre-auth.  We have bottom-line price validation that will catch any errors while we are able to preserve recording the proper tax amount.
This is an unblocker for M1 and core team decides on if and how to expand the shipping and tax endpoint to …
> Provides support for discount price changes at the time of shipping and tax estimations

- lib/Boltpay/DataDog/Client.php
Issue:
When the Bolt_Boltpay_OrderCreationException exception is thrown, the generated message has a status key in it. Datadog detects that it is an emergency and disregards the error severity passed in.
Proposed solution:
Generate a message instead of getting the JSON response as the error message for class Bolt_Boltpay_OrderCreationException
Code reference:
Bolt_Boltpay_OrderCreationException: https://github.com/BoltApp/bolt-magento1/blob/develop/app/code/community/Bolt/Boltpay/OrderCreationException.php#L163DataDog_Client: https://github.com/BoltApp/bolt-magento1/blob/develop/lib/Boltpay/DataDog/Client.php#L56
Asana task: https://app.asana.com/0/564264490825835/1128573212731792
> Datadog - Fix the OrderCreationException to resolve Datadog severity conflict

- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
- tests/unit/testsuite/Bolt/Boltpay/Model/ShippingAndTaxTest.php
Context:
Plugins potentially may expect or validate against the address data once it is saved.  Such an expectation was causing a problem at a merchant site for new customers that did not have default values already saved for shipping and billing addresses.
Fix:
This adds the full address info to a customer address prior to trying to saving it, which also cuts down on unnecessary double saves to the database.  Additionally, this sets a default billing address if none already exist. 
https://app.asana.com/0/941895179897714/1129037493381871
> Correct incomplete and improper saving of addresses during shipping and tax

- app/design/frontend/base/default/template/boltpay/replace.phtml
Asana task: https://app.asana.com/0/899238157173033/1116476869617025/f
This changes prevent double change buttons to Bolt button.
I added attribute, because we could not use style.display attribute of the element because of responsive design
> Added data-was-replaced attribute for replaced button

- app/code/community/Bolt/Boltpay/Model/Order.php
**Issue:**
If the discount applies to shipping, the discount price will be changed at the time of shipping and tax estimation, then pre-auth validation fails. Currently, this blocks an order from being able to process.
**Proposal solution:**
Skip total validation if the discount applies to shipping
> Skip total validation if discount applies to shipping

- app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
By moving the call to dispatching `bolt_boltpay_shipping_method_applied_before` to be directly before collecting totals and after performing all precondition logic, we allow for a full override of all the precondition logic, which is one of the expected benefits of the event.
https://app.asana.com/0/544708310157130/1130492400849229
> Dispatches bolt_boltpay_shipping_method_applied_before directly before collecting totals

- app/code/community/Bolt/Boltpay/Model/Order.php
This places the logic that was intended to be put in place for this config.
https://github.com/BoltApp/bolt-magento1/blob/develop/app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php#L290-L300
It enables logic to retain timestamps on preauth orders so that orders will appear in the normal flow of the Magento admin for merchants who wish to see these orders.
> Enables the preauth order timestamp switch option that was mistakenly forgetten

- app/code/community/Bolt/Boltpay/Model/Order.php
Our code base should move away from relying on client side data in any case that we can in order to avoid failures.  Furthermore, Bolt data is to be considered the source of truth for transactions.  For this reason, we continue with our pattern of using Bolt provided data for both quote and order lookups in preference to client side data stores.
> Rely on Bolt data and not merchant database for referenc to parent quote

- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
Clearing of address data has no point in order creation.  Whereas it may serve purpose after pre-fetching address data, it can only cause problems in order creation, and therefore is removed.
> Removes outdated address clearing from quote in order creation

- app/code/community/Bolt/Boltpay/controllers/ApiController.php
In the case of failed payment, (or something similar to what was previously called and orphaned transaction), the order potentially will be created and display_id updated at Bolt.  If this is the case, the order is already at the merchant site and needs to be looked up by increment id, which will now be the display ID.
https://app.asana.com/0/544708310157130/1130793273664830
> Lookup order by increment id after order has been created

- app/code/community/Bolt/Boltpay/Model/Traits/ValidatorTrait.php
- app/code/community/Bolt/Boltpay/Model/Validator.php
If extending of the Magento core is required, it is best to do it via trait to allow for multiple inheritance in the case where a 3rd-party module overrides the same class.  This prevents the need to redefine the entire methods of the Bolt class making it possible for simple upgrades.
https://app.asana.com/0/544708310157130/1131312115509169
Must fix autoloader for unit test to work
> Override Magento core by trait to allow for extension by referencing in custom code

- README.md
- app/code/community/Bolt/Boltpay/Helper/GeneralTrait.php
- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
Adds a filter event for Bolt Order data prior to it being completed and sent to the Bolt server.  This allows for additions of attributes and info derived from third party extensions which are currently ignored by our plugin.  One concrete example is third party user notes added prior to Bolt order creation time.
https://app.asana.com/0/941895179897714/1131668256595077
> Adds filter event for Bolt order data

- README.md
- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
I added a filter to allow custom discount modifications without the need to override the entire addDiscounts function. This is needed in cases where the default handling of discounts needs to be modified.
For example, let's say that a customer has a $100 subtotal in their cart and they have a $1,000 gift card. At the time of page load the calculated discount would be $100 since there is no shipping applied to the cart total yet. But if the discount is allowed to be applied to shipping as well, then when the shipping is applied during the shipping and tax estimation step, the $100 discount won't be enough to cover the shipping even though the customer has enough on the gift card. In this case we actually need to customize the discount amount at page load to be the full amount (e.g. $1,000) …
> Add filter if discount applies to shipping

- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
Modifications to PR #454 
This prevents the discount from being processed if the returned filter value is 0
> refactor the discount filter code to allow for skipping discount (i.e. amount = 0)

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
Somewhere along the lines, a refactor was missed where a method call that affects One Page Checkout in rare virtual cart will always fail.
https://github.com/BoltApp/bolt-magento1/blob/master/app/code/community/Bolt/Boltpay/Model/BoltOrder.php#L728
Fixes: https://app.asana.com/0/544708310157130/1132682963243986
> Moves protected method to the expected class

- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
The `bolt_boltpay_shipping_applied_to_bolt_order` event most naturally fits after the business logic has been processed for the task regardless of whether an actual method is added to the Bolt order.  If no shipping method was added after the application of this logic, it is still useful information for merchants, for instance, this could indicate that an in-store pickup is to be applied.
Fixes: https://app.asana.com/0/544708310157130/1132674635377298
> Always dispatch shipping applied to bolt order event at the end of routine

- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
Modifications to PR #454
Originally placed as PR #456 
This prevents the discount from being processed if the returned filter value is 0
Additional notes:
@johnmccombs1  wrote:
> Looks good. Were there cases where we were applying $0.00 discounts?
We can think of this in two ways.  The first is as in the description above -- that is, if the custom logic determines there is no discount, the processing should not do any further processing for that discount.  This is already in the original code as `&& $amount = $totals[$discount]->getValue()` in the if statement.  So, we are maintaining status quo.
The second way to think of it is that we want to allow away to fully override/skip the default behavior for a special sort of total -- perhaps something like points, or maybe a negative balance, …
> minor refactor of PR #454

- app/code/community/Bolt/Boltpay/controllers/ApiController.php
Many merchants have 3rd-party code that changes the status of the Bolt order to something other than pending_bolt.  For failed payments, we want to check that no transaction (e.g. verification of authorization) has occurred before cancelling and deleting the order.  Rather than relying on the status, it is more robust to view if any transactions have been recorded
Fixes: https://app.asana.com/0/544708310157130/1132600015873114
**WIP** pending testing in staging and merchant staging
> [WIP] Improve robustness of authorization/payment identification

- app/code/community/Bolt/Boltpay/Controller/Traits/WebHookTrait.php
- app/code/community/Bolt/Boltpay/Helper/LoggerTrait.php
- app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
- app/code/community/Bolt/Boltpay/Model/Observer.php
- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
- app/code/community/Bolt/Boltpay/etc/config.xml
To reduce processing time for create_order, we eliminate recalculation of shipping, which has been done sufficiently via the shipping and tax end point.  We also add the ability to log execution times via a benchmarking so that we may quantify processing time.
Fixes: https://app.asana.com/0/inbox/544708310157128/1132981769648030/1132983838706810
> Create order optimization with Benchmark Profiler

- app/code/community/Bolt/Boltpay/Model/Payment.php
- tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php
- tests/unit/testsuite/Bolt/Boltpay/ProductProvider.php
Orders rejected by Bolt with the inventory having never returned to the system. This addresses the issue
Fixes: https://app.asana.com/0/1125081140214268/1130067876286030
> Cancels orders via Magento to rollback inventory holds

- app/code/community/Bolt/Boltpay/Helper/Data.php
- app/code/community/Bolt/Boltpay/Model/Observer.php
- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
Adds the concept of orphaned transactions to 2.0.  This does two things:
1.)  Allows for orders to be created via webhook if the create_order endpoint times out 
2.)  Allows for non-pre-auth (legacy) orders to be processed by webhook
Additionally, this adds the user experience code of forwarding the user to the success_url when the Bolt create_order mechanism does not provide the forwarding URL
Fixes: https://app.asana.com/0/436430054069245/1132981769648030
> Address Pre-auth timeouted out orders, and v1.x orders

- app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
- app/design/frontend/base/default/template/boltpay/prefetch_shipping_quote.phtml
Originally posted at #472 
There are opportunities for errors in our shipping and tax endpoint. Here we cover four potential problems.
1.) We make sure we include the address data before attempting to save it in the case of 3rd-party address validation via observers
2.) We clobber exceptions when attempting to create a non-critical address book entry
3.) We do not call pre-fetch if there is no key for IpStack (when it is disabled)
4.) We do not cache empty shipping options
Fixes: https://app.asana.com/0/1123603852235561/1130717897778149
> Prevents errors in shipping and tax

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- app/code/community/Bolt/Boltpay/Controller/Traits/OrderControllerTrait.php
- app/code/community/Bolt/Boltpay/etc/system.xml
- tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
Currently configuration for auth capture can be set on magento backend, and this will override the Bolt Merchant admin configuration. Removing this will allow us to use the configuration on the merchant admin.
Fixes: https://app.asana.com/0/564264490825835/1132958531677445
> Remove authcapture parameter

- app/code/community/Bolt/Boltpay/Model/Payment.php
HOTFIX for 2.0.1 release
Originates from #443 
It turns out that it is not assured that state of the order is changed to cancel by calling the order cancel method.  To ensure this, we explicitly set the state.
Fixes: https://app.asana.com/0/1125081140214268/1130067876286030
> Rolls back the use of set state to ensure proper state after irreversible rejection

- app/code/community/Bolt/Boltpay/Model/Payment.php
HOTFIX for 2.0.1 release
Originates from #443
It turns out that it is not assured that state of the order is changed to cancel by calling the order cancel method. To ensure this, we explicitly set the state.
Fixes: https://app.asana.com/0/1125081140214268/1130067876286030
> Ensure that order state is updated to cancel on Bolt void

- app/code/community/Bolt/Boltpay/Helper/Data.php
In the multi-store context and in the caching context, Magento uses a placeholder "___SID" to store a session id on URLs.  This is post-processed upon rendering of the HTML and in single store context, or when it is not needed, it will be removed.  Because we are checking our required URL outside of the rendered context, we get differences between the final outputed URL and the pre-processed URL.  For our purposes, we want to process the URL prior to comparisons.
Fixes: https://app.asana.com/0/544708310157130/1135096267113402
> Frontend non-multistore URL pre-processing

- app/code/community/Bolt/Boltpay/Helper/DataDogTrait.php
Currently DataDog doesn’t track the plugin for Magento 1. Added it.
Fixes: https://app.asana.com/0/564264490825835/1128573212731793
> Set plugin-magento1 as a service for datadog

- app/code/community/Bolt/Boltpay/controllers/ApiController.php
It is more appropriate to use the immutable quote for the quote id in the success url in case third part software is in need of using the true quote data.
Fixes: https://app.asana.com/0/941895179897714/1135981781298153
> Use immutable quote id (real quote id) in success url

- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
Since the URL format is proving to be unpredictable, (e.g. with a trailing "/" or without), we will simplify by calling just checking for `prefetchEstimate` in the request.  Because this is isolated to the shipping controller, this is sufficient for identification.
Fixes: https://app.asana.com/0/941895179897714/1135898978484449
> Identify prefetch action by searching for prefetch in URL

- app/code/community/Bolt/Boltpay/Model/Payment.php
Merchant was reporting that several orders were stuck in Payment Review and they could not us the "Get Payment Update" button.  This forces an update on payment review orders, even if the bolt_transaction_status/hook history manages to get out of sync.
Fixes: https://app.asana.com/0/search/1137497898160001/1120933731228864
> Force Payment Update on payment review orders if transaction history is out of sync

- app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
- app/code/community/Bolt/Boltpay/Model/Observer.php
- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
This replaces PR #495 
Quotes are not being blocked for processing after failed_payment hooks.  After a create preauth order is deleted due to failed_payment, (after 10 minutes or immediately if that option is enabled), the quote would be reported as expired due to the order having been created. The manifestation of this in orphaned transactions is a failed webhook with the same error message.
This unblocks the quotes to allow orders to be re-created after failed_payments. 
Fixes: https://app.asana.com/0/inbox/544708310157128/1136200477398193/1136201003916971
> Fixes error of Cart has expired after failed_payment hook

- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
If an administrator uses a free shipping coupon, when collecting the shipping rates for the immutable quote, the initial shipping rates can’t be set to free since the address totals needed to be collected first.
Fixes: https://app.asana.com/0/564264490825835/1140088326262873
> Collect shipping address totals prior to collecting shipping rates

- app/code/community/Bolt/Boltpay/Model/Order.php
Magento looks up coupon codes in a case-insensitive way.  Our coupon code comparison should therefore follow suite.
Fixes: https://app.asana.com/0/941895179897714/1138749880537314
> Makes coupon code comparison case-insensitive

- README.md
- app/code/community/Bolt/Boltpay/Model/Coupon.php
- app/code/community/Bolt/Boltpay/Model/Order.php
If a customer is using a limited use coupon (e.g. one-time use coupon), and their initial auth fails (payment denied, etc), the failed hook deletes the order but doesn’t restore their coupon usage to not having been used. This fix restores the coupon usage to the pre-order creation state.
Fixes: https://app.asana.com/0/564264490825835/1139660501761065
> Reactivate used promotion after deleting failed order due to auth failure

- app/code/community/Bolt/Boltpay/Model/Payment.php
- tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php
**Issue:**
Whenever we cancel/void a transaction from Bolt, a void hook request is sent to Magento. It attempts to cancel the Magento order which sends back a void Bolt transaction and there is an exception that occurs as the Bolt transaction is already canceled.
**Proposal solution:**
Disable sending a void request to Bolt if the request is from Bolt
Fixes: https://app.asana.com/0/564264490825835/1139242847263129
> Disable sending void requests to Bolt if the request came from Bolt

- app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
- tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php
After investigating an error, i found that one argument is incorrect.:
```
unable to fetch shipping&Tax info for merchant:[411], division:[472]: APIError(47) Error while unmarshalling shipping and tax response: [200][Fatal error:  Call to a member function getMessage() on string in /usr/share/nginx/tadashishoji.com/app/code/community/Bolt/Boltpay/Helper/BugsnagTrait.php on line 107
```
Fixes: no link.
> Fixed passing argument in "notifyException" function.

- app/code/community/Bolt/Boltpay/Model/Payment.php
This prevents the following case:
The administrator creates an order which shows the current order status as Pending Bolt Authorization. They then comment on the order after Bolt has changed the status to something other than Pending Bolt Authorization and it changes the status back to Pending Bolt Authorization when the comment is submitted. This then causes the order to no longer show up in the admin order grid.
Fixes: https://app.asana.com/0/564264490825835/1139660501761068
> Prevent accidentally changing a processing order status to a pending bolt authorization status

- app/code/community/Bolt/Boltpay/Model/Payment.php
After creating a back-office order, the state is set to pending_payment. This introduces the possibility of recreating the bug stated in PR https://github.com/BoltApp/bolt-magento1/pull/511 as the dropdown status contains all of the statuses that belong to pending_payment including the pending_bolt status, see here https://screencast.com/t/CIyJK6POGY. Setting the state to “new” resolves this.
Fixes: https://app.asana.com/0/941895179897714/1141138267580345
> Set initial back-office order state to new

- app/code/community/Bolt/Boltpay/Model/Order.php
It has been observed in production that if orphaned transactions are initiated by Bolt, shipping and tax is not guaranteed to be calculated correctly on the quote.  Because of this, we absorb the extra hook processing time and for orphaned transactions, we force shipping recalculation.
Fixes: https://app.asana.com/0/544708310157130/1140705995930742
> Force shipping recalculation for orphaned transactions

- app/code/community/Bolt/Boltpay/Controller/Traits/WebHookTrait.php
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
- app/code/community/Bolt/Boltpay/controllers/ProductpageController.php
- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
Prevents duplicate API response output in all case.  It also implements the response in such a way that it can be flushed to Bolt while processing of other jobs can occur like third party post order creation code
Fixes: https://app.asana.com/0/941895179897714/1136224221711409/f
> Prevents duplicate JSON output + implement immediate response flushing

- app/code/community/Bolt/Boltpay/Model/Order.php
Older version of Magento like 1.9.0.1 and before do not support queuing emails.  We must add backwards support direct sending of emails for these versions
Fixes: https://app.asana.com/0/search/1143688623668737/1143055455198289
> Email Support for older Magento versions

- app/code/community/Bolt/Boltpay/Model/Payment.php
Fixes errors that were being thrown as a result of webhooks trying to void an already voided orders
Fixes: https://app.asana.com/0/inbox/544708310157128/1132767436522534/1142647842364511
https://app.bugsnag.com/bolt/magento/errors/5d95565a6419b9001b5d71a3?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[search][0][type]=eq&filters[search][0][value]=already&filters[search][1][type]=eq&filters[search][1][value]=voided
> Does not send void request to Bolt on hooks that cancel the order

- app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
Exception POST /boltpay/api/create_order
{ "status": "failure", "error": [{ "code": 2001003, "data": [{"reason": "Cart is empty"}] }] }
Fixes: https://app.asana.com/0/564264490825835/1144963049428593
> Set order_reference parameter to parent_quote_id in product checkout page

- app/code/community/Bolt/Boltpay/controllers/ApiController.php
- tests/unit/testsuite/Bolt/Boltpay/controllers/ApiControllerTest.php
There is a special case where the Bolt server is sending irreversibly rejected hooks for a transaction prior to the transaction being authorized.  Here we handle the case.
Fixes: https://app.asana.com/0/1125081140214268/1146176411053386/f
#changelog [bugfix] Handles immediate irreversibly rejected hook with no prior auth
> Handles immediate irreversibly rejected hook with no prior auth

- app/code/community/Bolt/Boltpay/controllers/ApiController.php
- tests/unit/testsuite/Bolt/Boltpay/controllers/ApiControllerTest.php
Failed_Payment hooks can send the piped format of display_id.  This situation was not handled and causes an order to be reported as canceled and handled when in fact it was not.  This adds support for the piped display_id
Fixes: https://app.asana.com/0/inbox/544708310157128/1146968193990481/1146969926976082
#changelog Handles the piped display ID case in failed_payment hooks
> Handles the piped display ID case in failed_payment hooks

- app/code/community/Bolt/Boltpay/Model/Cron.php
- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/etc/config.xml
- tests/unit/testsuite/Bolt/Boltpay/Model/CronTest.php
Initially proposed as PR #385
After a pre-auth pending order has existed for 15 minutes or more, we remove it from the system.
At this point, Bolt should have called the "failed_payment" webhook to do this. We are catching
the anomaly cases where this mechanism fails.  This will resolve any outstanding pending_payment Bolt orders on production servers.
Fixes: https://app.asana.com/0/1125081140214268/1146968193990481/f
#changelog  Internal order artifact cleanup routines
> Adds a defensive pre-auth order cron cleanup in case other mechanisms fail

- app/code/community/Bolt/Boltpay/Helper/ConfigTrait.php
- app/code/community/Bolt/Boltpay/Model/Observer.php
- app/code/community/Bolt/Boltpay/etc/config.xml
- app/code/community/Bolt/Boltpay/etc/system.xml
- tests/unit/testsuite/Bolt/Boltpay/Model/ObserverTest.php
Automatically create an invoice after creating the shipment 
Some merchants can’t capture until shipment, but also don’t want to have to manually capture once a shipment is created (e.g. ERP system generates a shipment, etc). This code allows merchants to auto-invoice after creating shipments.
Fixes: https://app.asana.com/0/564264490825835/1143014593457481
> Automatically create an invoice after creating the shipment 

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
array with empty value, but not empty arrray
if user unlogged and all groups are allowed bolt is disabled. This is not right
Fixes: https://app.asana.com/0/941895179897714/1142266855481737/f
\#changelog
- [+] Bug fix (change which fixes an issue)
- [+] Successfully tested locally (or docker image)
- [+] Successfully tested on a staging or sandbox server
- [+] Successfully tested on a merchant's staging server
> Fixed case, when all groups are allowed, that means that disable gropus

- tests/load/setup_files/CartDataLoadTest.php
- tests/load/setup_files/CartDataLoadTestController.php
- tests/load/setup_files/README.md
- tests/load/setup_files/setup.sh
This PR allows devs to easily setup a test store and expose an endpoint that triggers the part of the plugin that is responsible for turning a cart on M1 into a bolt order. This allows us to load test a part of the plugin that is not directly exposed by an endpoint. 
Note: The actual load tests will be included in a separate PR (https://github.com/BoltApp/bolt-magento1/pull/545)
Fixes: https://app.asana.com/0/941895179897714/1149771740841853/f
\#changelog
- [ x ] New feature (change which adds functionality)
- [ x ] Successfully tested on a staging or sandbox server
- [ x ] I have performed a self-review of my own …
> Expose an endpoint for LoadTesting

- app/code/community/Bolt/Boltpay/Helper/GeneralTrait.php
- app/design/frontend/base/default/template/boltpay/replace.phtml
- tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
Currently, if a merchant customizes their default add to cart process to use an Ajax request, after adding the first product to the cart, the initBoltButtons method isn’t available to initialize the Bolt button in the mini cart. This PR allows that method to be available even when the cart is empty but only executes it when the cart isn’t empty.
Fixes: https://app.asana.com/0/564264490825835/1149765095655042
#changelog Allow method initBoltButtons to be available even when the cart is empty
> Allow method initBoltButtons to be available even when the cart is empty

- tests/unit/testsuite/Bolt/Boltpay/controllers/ShippingControllerTest.php
Fixes: https://app.asana.com/0/544708310157130/1151537717819191
> Fixes 'hidden' failures in Bolt_Boltpay_ShippingControllerTest

- tests/unit/testsuite/Bolt/Boltpay/Model/CouponTest.php
Fixes: https://app.asana.com/0/544708310157130/1151537717819190
> Fixes 'hidden' failures in Bolt_Boltpay_Model_CouponTest

- tests/unit/testsuite/Bolt/Boltpay/Block/Rewrite/OnepageTest.php
Fixes: https://app.asana.com/0/544708310157130/1151537717819189
> Fixes 'hidden' failures in Bolt_Boltpay_Block_Rewrite_OnepageTest

- app/code/community/Bolt/Boltpay/controllers/ApiController.php
- tests/unit/testsuite/Bolt/Boltpay/controllers/ApiControllerTest.php
Fixes: https://app.asana.com/0/544708310157130/1151537717819188
> Fixes 'hidden' failures in Bolt_Boltpay_ApiControllerTest

- app/code/community/Bolt/Boltpay/Model/Cron.php
- tests/unit/testsuite/Bolt/Boltpay/Model/CronTest.php
Fixes: https://app.asana.com/0/544708310157130/1151537717819187
> Fixes 'hidden' failures in Bolt_Boltpay_Model_CronTest

- tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php
The price was incorrectly mismatched at 10 and 12.75.  This corrects this.  Also, unregistering of the the singleton mocks is best down after each test class so that there is no chance of accidental use in subsequent test classes.
Fixes: https://app.asana.com/0/search/1151708266934314/1150161568554697
> fixed incorrectly set price, correctly register/unregister mocks

- .circleci/config.yml
Integration tests were failing for month (!). It's probably false positive but I'd rather disable it until we can fix it and re-enable
https://app.asana.com/0/941895179897714/1152119232273305/f
> Kill integration test :/

- app/code/community/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateController.php
In order for the magic getter and setter methods to be able to find find the property as `$observer->getEvent()->getOrderCreateModel()` or `$observer->getOrderCreateModel()`, the array key must be set in snake case as `order_create_model`
Fixes: https://app.asana.com/0/941895179897714/1155064778904945
> Correct Varien Object Data Key Format

- app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
- tests/unit/testsuite/Bolt/Boltpay/Model/Admin/ExtraConfigTest.php
The extra config unit test revealed that there is an error in our code in handling the value of zero.  This corrects the interpretation of zero in the `getExtraConfig` method
Fixes: https://boltpay.slack.com/archives/CRGUZABC6/p1578076509001700
> Addresses error with zero set as an extra-config value

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
Refactor to code coverage 100% for Bolt_Boltpay_Block_Checkout_Boltpay + removal of erroneous legacy if statement `if (@!$cartData->error)`, which will always evaluate to true as 
```
$cartData = Mage::getModel('boltpay/boltOrder')->getBoltOrderTokenPromise($checkoutType);
```
returns a string, and will never have an `error` data member.
Fixes: https://app.asana.com/0/1131034199022699/1157340557191681
> Complete unit test for Bolt_Boltpay_Block_Checkout_Boltpay

- app/code/community/Bolt/Boltpay/Model/Order.php
Uses Bolt reported totals instead of calculated totals to avoid Magento backoffice capture mismatch errors
Fixes: https://app.asana.com/0/inbox/544708310157128/1158615664420009/1158616411800237
> [WIP] Uses Bolt reported totals instead of calculated totals to avoid capture mismatch

- app/code/community/Bolt/Boltpay/Model/Traits/ValidatorTrait.php
- tests/unit/testsuite/Bolt/Boltpay/Model/Traits/ValidatorTraitTest.php
Base rounding deltas cause percentage discounts applied to an order to often get off by $0.01 rounding errors because the validator used is a singleton. So every time collectTotals is called, it reuses the previous base rounding deltas and causes the rounding problems on the base grand total.
This PR resets the base rounding deltas to an empty array before collecting the total to prevent the rounding issue on the base grand total
Fixes: 
https://app.asana.com/0/564264490825835/1158615664420009
https://app.asana.com/0/564264490825835/1159584644406577
> Reset _baseRoundingDeltas property to an empty array before collecting the total

- app/code/community/Bolt/Boltpay/OrderCreationException.php
Small fix - `Throwable` is not available before PHP7 and causes an issue.
Fixes: https://app.asana.com/0/941895179897714/1159606703557921/f
\#changelog
> Change throwable reference to exception

- app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
- app/code/community/Bolt/Boltpay/Helper/Data.php
- app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
- app/design/frontend/base/default/template/boltpay/popup.phtml
- tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
Bolt server-side currently is not handling Product Page checkout out of stock errors.  A non-informative error is displayed that confuses users.  This adds a frontend quantity check to and displays a suitable error to the user if they attempt to order more than what is in stock.  If the order becomes out of stock while the user is browsing the product page, refreshing the browser will now solve the problem, consistent with the error message which Bolt currently displays.
Fixes: https://app.asana.com/0/544708310157130/1157626513145145
> Frontend quantity check for Product Page

- app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
- tests/unit/testsuite/Bolt/Boltpay/Model/Productpage/CartTest.php
In addition to frontend check, it is always possible that inventory may not be available in the middle of a product page checkout experience do to concurrent users ordering the same products.  Currently, the Bolt Server-side error message is does not support out of stock errors.  As a workaround solution, we disable the stock quantity backend checks during the create.order call, and instead defer this to pre-auth where out of stock messaging is supported
Fixes: https://app.asana.com/0/544708310157130/1157626513145145
> Product Page - Remove backend validation of available stock and defer it to pre-auth

- app/code/community/Bolt/Boltpay/Controller/Traits/WebHookTrait.php
- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
- tests/unit/testsuite/Bolt/Boltpay/Controller/Traits/WebHookTraitTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
- tests/unit/testsuite/Bolt/Boltpay/OrderHelper.php
Context:
There have been third party plugins creating orders that say payment method: Boltpay, but were not created by Bolt.  
Goal:
We want to prevent an order from being created with the the payment method boltpay if the submit isn't coming via webhooks, admin, or bolt product page flows.
Fixes: https://app.asana.com/0/544708310157130/1146170148693767
> Validate Bolt order creation origin

- app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
- tests/unit/testsuite/Bolt/Boltpay/Model/Productpage/CartTest.php
PPC does not happen in the context of a user accessible session and therefore there is no need for any immutable quote cloning.
Fixes: https://app.asana.com/0/544708310157130/1161793187073236
> PPC Refactor: Remove use of quote cloning

- app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
- tests/unit/testsuite/Bolt/Boltpay/Model/Admin/ExtraConfigTest.php
Currently, the back-office order status is "pending" and the default reception status configuration is "pending_bolt". So it throws an exception “Invalid webhook transition from pending to pending_bolt“ when the payment hook is sent to Magento to create an invoice for the back-office order.
This PR resolves that issue by adding "pending" status to the default reception statuses
Fixes: https://app.asana.com/0/564264490825835/1162923722970065
> Add pending status to the default reception statuses

- app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- app/code/community/Bolt/Boltpay/Helper/Data.php
- app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
- app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
- tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php
- tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/GeneralTraitTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/Productpage/CartTest.php
PPC currently exist in its own island doing a lot of repeat code.  This is not desirable.  Instead of repeating code, we send PPC Bolt Order creation down the same path as all other order creation.
Fixes: https://app.asana.com/0/941895179897714/1161793187073237
> PPC Refactor: Utilize Bolt_Boltpay_Model_BoltOrder and Bolt_Boltpay_Block_Checkout_Boltpay

- app/code/community/Bolt/Boltpay/Helper/GeneralTrait.php
- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/GeneralTraitTest.php
Fix images for products with variants are not populated correctly. Instead of getting product directly from quote item, we retrieve it using the sku, which is unique for variants.
Fixes: https://app.asana.com/0/1133951978134395/1155920207408049
#changelog Fix images for products with variants are not populated correctly
> Fix variant image

- app/code/community/Bolt/Boltpay/controllers/ProductpageController.php
- tests/unit/testsuite/Bolt/Boltpay/controllers/ProductpageControllerTest.php
We want to use a common method for hook verification, extraction of request body and sending of responses including identifying PPC as a webhook request.  This is all handled in WebhookTrait and ProductPageController should be using this.
Fixes: https://app.asana.com/0/941895179897714/1161793187073238
#changelog  Product Page integration into core system
> Refactor ProductPageController to use WebhookTrait

- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
quote parameter is not used inside the method. What may ultimately be more important is that it wasn't being provided in the call which usually only results in warning logged but in developer mode or PHP>=7.1 will throw an exception
https://www.php.net/manual/en/migration71.incompatible.php#migration71.incompatible.too-few-arguments-exception
https://github.com/GuaranteedNetwork/bolt-magento1/blob/6c3d8da28ffe482d9ff9b8ad036dcb3ac1768403/app/code/community/Bolt/Boltpay/Model/BoltOrder.php#L287
Fixes: https://app.asana.com/0/941895179897714/1163884592458094
#changelog Bugfix: Provide missing default parameter for Bolt_Boltpay_Model_BoltOrder::addShippingForAdmin
> Supply default value for optional parameter for Bolt_Boltpay_Model_BoltOrder::addShippingForAdmin

- app/code/community/Bolt/Boltpay/Model/Order.php
- tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
We used the following logic to send the total amount to Bolt:
**round($item->getCalculationPrice() * 100) * $item->getQty()**
See here: https://www.screencast.com/t/D9HFAy63x
So when the create_order hook is sent to Magento to create the order, we must use the same logic to validate it.
Fixes: 
https://app.asana.com/0/564264490825835/1163958531351617
https://app.asana.com/0/564264490825835/1163433085577459
\#changelog Correct the total validation logic when the create_order hook is sent to Magento 
> Correct the total validation logic when the create_order hook is sent to Magento 

- .github/CODEOWNERS
Removing @ryan-timothy-albert from codeowners
#changelog Removing @ryan-timothy-albert from codeowners
> Update codeowners - removing Ryan

- app/code/community/Bolt/Boltpay/Model/Order.php
- tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
Currently, we use the product ID instead of cart ID for the reference that is passed to Bolt and then rely on the product not being able to be found by ID. While most of the time this is ok, there exists a remote opportunity for the product ID to match the cart item ID and validation to fail.
Instead, we wish to use the product ID matched against the cart item to validate the cart item price
Fixes: https://app.asana.com/0/941895179897714/1165040796588172
#changelog PPC Item Validation by Product ID
> PPC Validate Items by Product ID

- app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
- app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
- tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php
Add support for downloadable products on PPC. During validation, if customer is not logged in and product is downloadable, ask the customer to login and redirect him back to product page after login if not disabled by 'Redirect Customer to Account Dashboard after Logging in' configuration.
Fixes: https://app.asana.com/0/941895179897714/1165040796588166
#changelog Product Page Checkout - Adds Downloadable Product support
> PPC Downloadable Product w/ login required support

- app/code/community/Bolt/Boltpay/Model/Order.php
- tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
Remove Boltpay from failed preauth order quotes in order to prevent third party modules from placing Bolt orders
Fixes: https://app.asana.com/0/inbox/544708310157128/1161099143858659/1164932369617130
#changelog Remove payment method for failed preauth order quotes
> Remove payment method for failed preauth order quotes

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- app/code/community/Bolt/Boltpay/Helper/Data.php
- tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
Recently, changes were made to BoltCheckout.configure which breaks the use of calling this method from the check callback.  We therefore take an alternative approach to deferred configuration for Admin and Firecheckout where we must first validate the forms before BoltCheckout.configure can can be provided with proper data.
Note: This is a functional implementation of the request to be available at the soonest release and it is not for style points.  This code will be refactored in the future to simplify it's understanding.
Fixes: https://app.asana.com/0/544708310157130/1164240591833289
#changelog Remove BoltCheckout.configure from check callback in Admin and Firecheckout
> Remove BoltCheckout.configure from check callback in Admin and Firecheckout

- .circleci/config.yml
- tests/scripts/ci.sh
- tests/scripts/magento_install.sh
- tests/scripts/run_phpunit_tests.sh
We already have coverage with the 5.6 tests, so it's kinda redundant. Now everything completes in like 3 minutes, as opposed to 20+ minutes before.
#changelog Make tests run faster by disabling coverage for 5.5
> [M1P-20] Make tests run faster by disabling coverage for 5.5

- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
- tests/unit/testsuite/Bolt/Boltpay/Model/BoltOrderTest.php
Upon changing unserialize to json_decode, the conversion from serialized string to array was changed to serialized string to object.  This fixes the issue by returning the expected array
Fixes: https://app.asana.com/0/inbox/544708310157128/1167010772454833/1167039107816210
https://boltpay.slack.com/archives/CKBBANKD2/p1584483491048700?thread_ts=1584483356.047600&cid=CKBBANKD2
#changelog HOT FIX: Deserialize to expected array instead of object
> HOT FIX: Deserialize to expected array instead of object

- app/code/community/Bolt/Boltpay/Model/Payment.php
- tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php
In certain circumstances, an amount's value of zero can be sent, for example, if the complete invoice has already been refunded using store credit. This will then result in an exception by the Bolt API. Instead, do not send a refund request to Bolt of this nature.
Fixes: https://app.asana.com/0/941895179897714/1167296894232481
#changelog Bugfix: Online refund less than 0.01 will be ignored by Bolt
> Do not make a call to Bolt if online refund amount is less than 0.01

- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
- tests/unit/testsuite/Bolt/Boltpay/Model/BoltOrderTest.php
-- from inline code comment --
Attempting to reset some of the values already set by merge affects the totals passed to
Bolt in such a way that the grand total becomes 0. Since we do not need to reset these values we ignore them all.
Fixes: https://app.asana.com/0/941895179897714/1168370828754618
#changelog Updates cloned quote to correctly address commented issue
> [M1P-26] Updates cloned quote to correctly address commented issue

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
[ENG-518] Check container exists before calling configureProductCheckout
Fixes: https://app.asana.com/0/1133951978134395/1167936044773634
#changelog [ENG-518] Check container exists before calling configureProductCheckout
[ENG-518]: https://boltpay.atlassian.net/browse/ENG-518
> [ENG-518] Check container exists before calling configureProductCheckout

- app/code/community/Bolt/Boltpay/Helper/GeneralTrait.php
- app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
- app/code/community/Bolt/Boltpay/Model/Observer.php
- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/controllers/ApiController.php
- app/code/community/Bolt/Boltpay/etc/config.xml
- tests/unit/testsuite/Bolt/Boltpay/Model/Admin/ExtraConfigTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/CronTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/ObserverTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php
- tests/unit/testsuite/Bolt/Boltpay/OrderHelper.php
This more accurately implements the logic to safeguard Bolt pre-auth order status from being changed by other 3rd party plugins.  The previous attempt failed in production for a variety of reasons including order models not being loaded, and adding preventative steps after the problem had already occured 
Fixes: https://app.asana.com/0/941895179897714/1163546160576133
https://app.asana.com/0/941895179897714/1165390780167868
#changelog Safeguards Bolt Orders from 3rd Party code
> Safeguards Bolt Orders from 3rd Party code

- app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- app/code/community/Bolt/Boltpay/Helper/ConfigTrait.php
- app/code/community/Bolt/Boltpay/Helper/Data.php
- app/code/community/Bolt/Boltpay/Model/BoltOrder.php
- app/code/community/Bolt/Boltpay/Model/Order.php
- app/code/community/Bolt/Boltpay/OrderCreationException.php
- app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
- app/design/frontend/base/default/template/boltpay/popup.phtml
- tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/ConfigTraitTest.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/BoltOrderTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
- tests/unit/testsuite/Bolt/Boltpay/OrderCreationExceptionTest.php
If we enable Minimum Order Amount in M1 (Admin dashboard -> Store -> Configuration -> Sales -> Sales -> Minimum Order Amount ) and set a Minimum Amount, in the frontend shop, even when the cart subtotal is less than the minimum amount, the customer can still open Bolt modal and process to payment, and eventually will get an error for the restriction.
The Minimum Order Amount is a native setting in M1, so the Bolt plugin should support it.
Fixes: https://app.asana.com/0/941895179897714/1166832552917026
#changelog Add minimum order amount support
> [M1P-29] Add minimum order amount support

- app/code/community/Bolt/Boltpay/Controller/Traits/WebHookTrait.php
- tests/unit/testsuite/Bolt/Boltpay/Controller/Traits/WebHookTraitTest.php
When not exiting immediately, the Magento's controller dispatch method will always call again sendResponse, which can result duplicate replies to Bolt.  This can be prevented by emptying the response body after and call to sendResponse is sent.
Fixes: https://boltpay.atlassian.net/browse/M1P-30
#changelog [M1P-30] Empty response body after sending to avoid duplicate response
> [M1P-30] Empty response body after sending to avoid duplicate response

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
https://github.com/GuaranteedNetwork/bolt-magento1/blob/6b1d76bd8c1590622c9e74fb29d49611c1a9005f/app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php#L215
breaks the PPC code because there is a syntax error where a  `var` declaration is being attempted to be used as an expression of an assignment statement for window.BoltModal
https://github.com/GuaranteedNetwork/bolt-magento1/blob/6b1d76bd8c1590622c9e74fb29d49611c1a9005f/app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php#L239
Fixes: https://boltpay.atlassian.net/browse/M1P-36
#changelog [M1P-36] PPC javascript error in Bolt configure call
> [M1P-36] PPC javascript error in Bolt configure call

- app/code/community/Bolt/Boltpay/Model/Coupon.php
- tests/unit/testsuite/Bolt/Boltpay/Model/CouponTest.php
Error is returned if discount applied via the Bolt modal drops price below minimum order amount but is not displayed in an elegant way in the front-end.  The discount API provides a means to handle this
Resolution:
Fixes: 
https://app.asana.com/0/544708310157130/1169776517444409
https://app.asana.com/0/544708310157130/1169757710813673
#changelog Discount API minimum order amount validation
> [WIP] Discount API minimum order amount validation

- app/design/adminhtml/default/default/template/boltpay/form.phtml
Currently, we always show Bolt dropdown UI in the admin order creation page (see here: https://prnt.sc/rz0ioj) but Bolt is useless unless the Publishable Key - Backoffice is configured. This PR adds a message indicating you need to set the key (see here: http://prntscr.com/rz51vg) as the M2 flow https://github.com/BoltApp/bolt-magento2/pull/624
Fixes: https://app.asana.com/0/564264490825835/1171215790723561
#changelog Show notice message in backoffice when the key is not set
> Show notice message in backoffice when the key is not set

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
Bolt core code has changed the address values for Apple Pay which requires us to change our Apple Pay address detection logic to exclude in prefills.
old sentinels:
email - fake@email.com
phone - 1111111111
new sentinels
email - na@bolt.com
phone - 8005550111
addressLine1 - tbd
Fixes: https://boltpay.atlassian.net/browse/M1P-43
#changelog Update Apple Pay sentinels for hints prefill exclusion
> Update Apple Pay sentinels for hints prefill exclusion

- app/code/community/Bolt/Boltpay/controllers/ShippingController.php
- tests/unit/testsuite/Bolt/Boltpay/controllers/ShippingControllerTest.php
Bolt core code has changed the address values in the Apple Pay request for the shipping and tax call which requires us to change our Apple Pay pseudo-address detection logic.
Old detection code: 
https://github.com/BoltApp/bolt-magento1/blob/master/app/code/community/Bolt/Boltpay/controllers/ShippingController.php#L381-L398
New format of JSON:
{
"reference": "5470883",
...
"shipping_address": {
"street_address1": "tbd",
"street_address2": null,
"street_address3": null,
"street_address4": null,
"locality": "Goodyear",
"region": "Arizona",
"postal_code": "85338",
"country_code": "US",
"country": "United States",
**"name": "tbd",   //value has been changed from “n/a” which we used**
"first_name": "tbd",
"last_name": "tbd",
"company": null,
"phone": "8005550111",
"email": "na@bolt.com"
},
... …
> Update shipping and tax request ApplePay detection

- app/code/community/Bolt/Boltpay/Model/Payment.php
- tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php
When applying refunds from the Bolt merchant dashboard, it is currently impossible to tell if and which inventory items should be returned. Magento provides a directive for this in the native admin as shown below.
Because of this, we should not attempt to handle inventory if the refund is issued from the Bolt merchant dashboard.
Fixes: https://boltpay.atlassian.net/browse/M1P-44
#changelog Remove Inventory handling from merchant dashboard refunds
> Remove Inventory handling from merchant dashboard refunds

- app/code/community/Bolt/Boltpay/Controller/Traits/WebHookTrait.php
- tests/unit/testsuite/Bolt/Boltpay/Controller/Traits/WebHookTraitTest.php
`controller_front_send_response_after` event is usually dispatched with front parameter pointing to a `Mage_Core_Controller_Varien_Front`.  Missing this can cause observers to fail, like `Mage_Persistent_Model_Observer_Session::synchronizePersistentInfo`
Fixes: https://boltpay.atlassian.net/browse/M1P-45
#changelog Add missing event parameter for controller_front_send_response_after
> Add missing event parameter for controller_front_send_response_after

- app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
Unable to open PPC checkout in IE 11 due to the use of the method `forEach` which is not supported in this browser.
Fixes: https://boltpay.atlassian.net/browse/M1P-49
#changelog Replaces forEach method to be compatible with IE11
> Replaces forEach method to be compatible with IE11

- app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
- app/code/community/Bolt/Boltpay/etc/system.xml
- tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
Bolt configuration currently doesn't provide an option to prevent NOT LOGGED IN users from using Bolt Checkout. This PR extends existing Disabled Customer Groups configuration to include NOT LOGGED IN as option, updates detection logic to properly handle new group id (beause it is 0).
Fixes: https://boltpay.atlassian.net/browse/M1P-52
#changelog Add support for preventing not logged in users from using Bolt
> Add support for preventing not logged in users from using Bolt

- tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/ConfigTraitTest.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/DataDogTraitTest.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
- tests/unit/testsuite/Bolt/Boltpay/Helper/GraphQLTraitTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/Admin/ExtraConfigTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/FeatureSwitchTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/ObserverTest.php
- tests/unit/testsuite/Bolt/Boltpay/OrderCreationExceptionTest.php
- tests/unit/testsuite/Bolt/Boltpay/controllers/ConfigurationControllerTest.php
Codecov is falsely displaying 100% code coverage. 
This test update takes code coverage to 100% and removes false positives by adding the missing `@covers` annotation in test methods. 
Fixes: https://boltpay.atlassian.net/browse/M1P-55
#changelog Unit Test: Implement uncovered methods and Remove False Positives
> Unit Test: Implement uncovered methods and Remove False Positives

- app/code/community/Bolt/Boltpay/Model/Updater.php
- tests/unit/autoload.php
- tests/unit/testsuite/Bolt/Boltpay/Model/UpdaterTest.php
There is a known Magento 1 and 2 bug involving HTTP/2 and Magento Connect/Magento Marketplace where the header error detection is not correctly implemented. This pull request allows for graceful fallback to custom code if the Magento libraries fail.
see:
https://magento.stackexchange.com/questions/249737/magento-2-invalid-response-line-returned-from-server-http-2-200
https://community.magento.com/t5/Magento-2-x-Version-Upgrades/Sign-in-to-Magento-Marketplace-gt-quot-Invalid-response-line/td-p/111720
Fixes: https://boltpay.atlassian.net/browse/M1P-63
#changelog Address Magento bug with HTTP/2 and Magento Connect request
> Address Magento bug with HTTP/2 and Magento Connect request [M1P-63]

- app/code/community/Bolt/Boltpay/Block/Adminhtml/Notification.php
- app/code/community/Bolt/Boltpay/Model/FeatureSwitch.php
- app/code/community/Bolt/Boltpay/Model/Observer.php
- tests/unit/testsuite/Bolt/Boltpay/Block/Adminhtml/NotificationTest.php
- tests/unit/testsuite/Bolt/Boltpay/Block/Adminhtml/UpdatePopupTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/FeatureSwitchTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/ObserverTest.php
Like all new massive features, we gate admin notifications behind a feature switch
Fixes: https://boltpay.atlassian.net/browse/M1P-66
#changelog Gate admin notifications when Bolt is updated behind a feature switch
> Gate admin notifications when Bolt is updated behind a feature switch

- app/code/community/Bolt/Boltpay/Block/Info.php
- app/code/community/Bolt/Boltpay/Model/Payment.php
- app/code/community/Bolt/Boltpay/etc/config.xml
- app/design/adminhtml/default/default/template/boltpay/info/default.phtml
- app/design/frontend/base/default/template/boltpay/info/default.phtml
- tests/unit/testsuite/Bolt/Boltpay/Block/InfoTest.php
- tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php
There is no way to identify that an order was a PayPal/APM purchase through Bolt within M1.
So we need to add support for displaying info Paypal/APM info in the order details.
Fixes: https://boltpay.atlassian.net/browse/M1P-67
#changelog Fix display of APM/PayPal Transactions within Magento 1 Dashboard
> M1P-67 Fix display of APM/PayPal Transactions within Magento 1 Dashboard

- .circleci/config.yml
- tests/scripts/setup_and_test.sh
The tool n98-magerun we use for M1 installing doesn't support PHP5.5 from its version 2.0
So we need to use previous tool version for PHP5.5 workflow.
Fixes: [MA-50]
#changelog MA-50 Use old version of n98-magerun for PHP5.5
[MA-50]: https://boltpay.atlassian.net/browse/MA-50
> MA-50 Use old version of n98-magerun for PHP5.5
