app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/Helper/Api.php

Just realized that I never created a pull request for this.

Bug shipping discount tax

---

app/code/community/Bolt/Boltpay/Helper/Api.php
app/code/community/Bolt/Boltpay/controllers/ApiController.php
app/code/community/Bolt/Boltpay/controllers/ShippingController.php

https://app.asana.com/0/436430054069245/614370607072692

order reference used in place of display id to retrieve quotes

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/controllers/ApiController.php
app/code/community/Bolt/Boltpay/controllers/OrderController.php

frontend, order save, frontend will simply forward to the success page

Removed racing condition sleeps and simplified to if webhooks beat the

---

app/code/community/Bolt/Boltpay/Helper/Api.php

refer to asana task https://app.asana.com/0/436430054069245/685583960912802/f

correct shipping and  tax calculation for virtual cart

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/etc/config.xml
app/code/community/Bolt/Boltpay/etc/system.xml

refer to task https://app.asana.com/0/436430054069245/687896447182745/f

Make merchant scoped account optional feature and disable by default

---

.travis.yml
app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/Helper/Bugsnag.php
tests/unit/testsuite/Bolt/Boltpay/Model/ObserverTest.php

- Set the bugsnag environment for the PHPUnit test.
- Refactoring the legacy code for tests

PhpUnit Tests 

---

app/code/community/Bolt/Boltpay/Helper/Api.php
app/code/community/Bolt/Boltpay/Model/Payment.php

https://app.asana.com/0/436430054069245/707259610619785

Allows Bolt to define the order status prior to webhooks

---

app/code/community/Bolt/Boltpay/Model/Payment.php

https://app.asana.com/0/544708310157130/694809648828326

hotfix: correction for strict parameter type checking in overridden methods

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/Helper/Data.php

https://app.asana.com/0/544708310157130/710610548302228

Moves the cloning of a quote to the helper class

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php

https://app.asana.com/0/544708310157130/713162692866472

assures that email is added to the prefill values for admin modal

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php

Firecheckout/OnePageCheckout prevent Bolt Order Creation if no shipping method is specified

---

app/code/community/Bolt/Boltpay/Model/Observer.php
app/code/community/Bolt/Boltpay/Model/Payment.php

https://app.asana.com/0/544708310157130/707109894457835
https://app.asana.com/0/544708310157130/687916964711091

Adds unhold logic while preventing hooks from unholding orders

---

app/code/community/Bolt/Boltpay/Model/Payment.php
app/code/community/Bolt/Boltpay/controllers/ShippingController.php

It was missed correct values in required field for shopping cart price rule calculation.
What i did:
- add field region_id
- switch value in region variable from code to name.
The Task - https://app.asana.com/0/436430054069245/722153711450199/f

Fix the problem with shopping cart price rules conditions.

---

app/code/community/Bolt/Boltpay/Model/Observer.php

Copy code from https://github.com/BoltApp/bolt-magento1/pull/68 to make review of #68 easier.

Fix for one penny diff

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php

Introduced in https://github.com/BoltApp/bolt-magento1/pull/68 and #104

Fix argument of _createBoltOrder 

---

app/code/community/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateController.php
js/boltpay/admin_order.js

https://app.asana.com/0/544708310157130/729388163223159

Additions to admin order code to work in the context of v1.1.6

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/controllers/ShippingController.php
app/code/community/Bolt/Boltpay/etc/system.xml
app/design/frontend/base/default/template/boltpay/prefetch_shipping_quote.phtml

https://app.asana.com/0/436430054069245/733119829814643/f

Replace freegeoip code to ipstack & make prefetchEstimate work

---

app/code/community/Bolt/Boltpay/Model/Payment.php

https://app.asana.com/0/436430054069245/734583198970750/f
Now it does not trigger void when cancel the order it is because we miss the authorization transaction.

Add authorization transaction when authorized by bolt

---

app/code/community/Bolt/Boltpay/Block/Adminhtml/System/Config/Form/Button.php
app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/Helper/Api.php
app/code/community/Bolt/Boltpay/Helper/Data.php
app/code/community/Bolt/Boltpay/Model/Payment.php
app/code/community/Bolt/Boltpay/controllers/ConfigurationController.php
app/code/community/Bolt/Boltpay/etc/config.xml
app/code/community/Bolt/Boltpay/etc/system.xml
app/design/adminhtml/default/default/template/boltpay/system/config/button.phtml
app/design/frontend/base/default/template/boltpay/track.phtml
create_release.sh
tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
tests/unit/testsuite/Bolt/Boltpay/Helper/ApiTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php
tests/unit/testsuite/Bolt/Boltpay/controllers/ShippingControllerTest.php

Here is the task description:
Currently we have settings in magento admin. System->Configuration->Payment Method->Bolt Pay
Add "Check configuration" here to run following checks:
- If API key, signing secret, and at least one publishable key is set
- Make API request to merchant/order API with fake data. Show error if response is not 2xx
- Verify db has all schema defined in https://github.com/BoltApp/bolt-magento1/tree/develop/app/code/community/Bolt/Boltpay/sql/bolt_boltpay_setup_

Initial test button configuration.

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/Helper/Api.php
app/code/community/Bolt/Boltpay/Helper/Data.php
app/code/community/Bolt/Boltpay/Helper/Url.php
app/code/community/Bolt/Boltpay/Model/Observer.php
app/code/community/Bolt/Boltpay/Model/Payment.php
app/code/community/Bolt/Boltpay/controllers/ConfigurationController.php
tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
tests/unit/testsuite/Bolt/Boltpay/Helper/ApiTest.php

https://app.asana.com/0/0/742639555331388/f

Refactor url related logic to one file

---

app/code/community/Bolt/Boltpay/Helper/Api.php
app/code/community/Bolt/Boltpay/controllers/OrderController.php

Looks up order by `order_reference` which is much more reliable than `increment_id/display_id`

Looks up order by order reference

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/design/adminhtml/default/default/layout/boltpay.xml
app/design/adminhtml/default/default/template/boltpay/connectjs.phtml
app/design/adminhtml/default/default/template/boltpay/form.phtml
js/boltpay/admin_order.js

There are a couple of issues addressed here with the admin.
The first major issue was with errors caused by multiple loads of connect.js.  It was ok before, but now it is not.  The fix was simply to load connect.js once and reload the Bolt Button as many times as needed.  *This may also provide a solution for switching between multi-step and one-page keys.*ly
Secondly, preloading the address fields has been fixed.

Admin order updates

---

app/code/community/Bolt/Boltpay/etc/system.xml

https://app.asana.com/0/436430054069245/756982959124649/f

Enables individual store configuration

---

app/code/community/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateController.php

This branch fixes two errors in the admin order creation.
1.) It acknowledges other payment method types and differs to Magento to process these other methods
2.) It uses the immutable quote/parent quote construct in order for webhooks to succeed on admin created Bolt orders
additionally, we assure that the admin is notified to calculate shipping in all scenarios.

Admin order webhook and other payment method support

---

app/code/community/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateController.php

Branch rebased to the origin/develop HEAD

Admin order refactor

---

app/code/community/Bolt/Boltpay/Helper/Api.php
tests/unit/testsuite/Bolt/Boltpay/Helper/ApiTest.php

Fixed bug in calculating shipping discounts.

Bug fix shipping discounts

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/Helper/Api.php
app/code/community/Bolt/Boltpay/Model/Api2/Order/Rest/Admin/V1.php
app/code/community/Bolt/Boltpay/Model/Observer.php
app/code/community/Bolt/Boltpay/Model/Payment.php
app/code/community/Bolt/Boltpay/controllers/ApiController.php
app/code/community/Bolt/Boltpay/controllers/ConfigurationController.php
app/code/community/Bolt/Boltpay/controllers/OrderController.php
app/code/community/Bolt/Boltpay/controllers/ShippingController.php

task https://app.asana.com/0/436430054069245/695464419655877/f

Update string usage for future translation

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/Helper/Api.php
app/design/adminhtml/default/default/template/boltpay/system/config/button.phtml
app/design/frontend/base/default/template/boltpay/prefetch_shipping_quote.phtml
app/design/frontend/base/default/template/boltpay/replace_firecheckout.phtml
tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php

The custom function checks if the store/request is secure and then adds the "_secure" key with value set to true as an additional parameter.

[WIP] Wrap Magento's getUrl() with custom function

---

js/boltpay/admin_order.js

This gives an easy entry point for manipulating the admin form javascript

adds hook for admin order javascript

---

app/code/community/Bolt/Boltpay/controllers/OrderController.php

https://app.asana.com/0/544708310157130/770550762170012

assures shipping method is set on firecheckout order creation call

---

app/code/community/Bolt/Boltpay/etc/system.xml

- Multistep key is a default option for all merchants to move it to top
- Backoffice is the second important so move to second, also add comment

Rename publishable key options and reorder

---

app/design/frontend/base/default/template/boltpay/replace.phtml

https://app.asana.com/0/436430054069245/796327971644142/f

Use DOMContentLoaded instead of onload to initialize the Bolt checkout button

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/design/frontend/base/default/layout/boltpay.xml
app/design/frontend/base/default/template/boltpay/popup.phtml
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

Ticket - https://github.com/BoltApp/bolt-magento1/pull/185

Popup Magento instead of alert

---

app/code/community/Bolt/Boltpay/Model/Order.php
app/code/community/Bolt/Boltpay/controllers/ApiController.php

https://app.asana.com/0/544708310157130/840291753945716

Clears orphaned transaction cart after order creation

---

app/design/frontend/base/default/layout/boltpay.xml

Issue https://github.com/BoltApp/bolt-magento1/issues/213

#213 Move popup to the end of body.

---

app/code/community/Bolt/Boltpay/Helper/Api.php

We already has version in separate header but having this in user-agent is convenient when reading logs

Add plugin version to user-agent

---

app/code/community/Bolt/Boltpay/Model/Order.php

task https://app.asana.com/0/436430054069245/856456371749074/f

Added firstname and lastname if customer is guest.

---

app/code/community/Bolt/Boltpay/Helper/Bugsnag.php

Task - https://app.asana.com/0/436430054069245/864362321992590/f

Added store_url to the breadcrumbs of Bugsnag.

---

app/code/community/Bolt/Boltpay/Model/Payment.php

Adds get payment update to captured transactions for payments that are

---

app/code/community/Bolt/Boltpay/Helper/Api.php

Hooks should be a way to retry

Remove retry of fetch transaction

---

app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
tests/unit/testsuite/Bolt/Boltpay/Model/ShippingAndTaxTest.php

Task - https://app.asana.com/0/436430054069245/897605539326591/f

Prevent php notices from stdClass

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/Helper/Data.php
app/code/community/Bolt/Boltpay/etc/system.xml
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

https://app.asana.com/0/544708310157130/964192980673396
Adds the onEmailEnter event to the Magento Admin

Adds on email enter event to Magento 1

---

app/code/community/Bolt/Boltpay/Model/BoltOrder.php
tests/unit/testsuite/Bolt/Boltpay/Model/BoltOrderTest.php

Asana task: https://app.asana.com/0/564264490825835/962316257634287

Add support for item properties

---

app/code/community/Bolt/Boltpay/Model/Order.php
app/code/community/Bolt/Boltpay/Model/OrderFixer.php
app/code/community/Bolt/Boltpay/Model/Payment.php
app/code/community/Bolt/Boltpay/controllers/OrderController.php
app/code/community/Bolt/Boltpay/etc/config.xml
app/code/community/Bolt/Boltpay/etc/system.xml
tests/unit/testsuite/Bolt/Boltpay/CouponHelper.php
tests/unit/testsuite/Bolt/Boltpay/Model/CouponTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/OrderFixerTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
tests/unit/testsuite/Bolt/Boltpay/OrderHelper.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

Asana task: https://app.asana.com/0/564264490825835/944238406055904

Prototype solution for price mismatches

---

app/code/community/Bolt/Boltpay/Model/Payment.php

Context asana task https://app.asana.com/0/941895179897714/952884481796430/f
When doing a refund from the Bolt dashboard, it is hard to detect what the refund is for, the merchant can enter random amount in partial refund for various purpose, and the refund could be shipping, tax, item fee or any part of them. Therefore we have to reply on "Adjustment Refund", using this field the refund in magento can keep pace with exact amount from Bolt server, also avoid complicated calculation and conflicts with other plugins.

Do a refund from the Bolt dashboard properly

---

app/design/frontend/base/default/template/boltpay/replace_firecheckout.phtml

https://app.asana.com/0/544708310157130/983210151956780

changes to classic form of `for` loop instead of `foreach` for IE11

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php

Asana task: https://app.asana.com/0/564264490825835/1001418990816170

Prefill the default shipping address for logged in customer

---

app/code/community/Bolt/Boltpay/Model/Payment.php

Asana task: https://app.asana.com/0/564264490825835/998110620016248

Move update payment status after order save

---

app/code/community/Bolt/Boltpay/Model/Order.php
app/code/community/Bolt/Boltpay/controllers/ApiController.php
app/code/community/Bolt/Boltpay/controllers/OrderController.php

Asana task: https://app.asana.com/0/564264490825835/1108525009378275

Ensure customer is logged in when saving the order

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php

https://app.asana.com/0/544708310157130/1108368077993436
Provides an easy means to make changes to the BoltCheckout default javascript. 
-----------------------------------------------------
**Simple example [Adding variables before BoltCheckout.configure for callback use, method call after]:** 
_in config.xml_
```
...
<events>
<bolt_boltpay_filter_bolt_checkout_javascript>
<observers>
<bolt_boltpay_prepend_variables_postfix_method_call>
<class>Bolt_Custom_Model_Observer</class>
<method>addCustomVariablesAndMethodsToJS</method>
</bolt_boltpay_prepend_variables_postfix_method_call>
</observers>
</bolt_boltpay_filter_bolt_checkout_javascript>
</events>
```
_in the Bolt_Custom_Model_Observer class_
```
/**
* Adds custom javascript to BoltCheckout javascript
*
* @param Varien_Event_Observer …
```

Javascript filter event

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/Helper/Data.php

https://app.asana.com/0/544708310157130/1108368077993436
Provides an easy means to make changes to the BoltCheckout default javascript. 
-----------------------------------------------------
**Simple example [Adding variables before BoltCheckout.configure for callback use, method call after]:** 
_in config.xml_
```
...
<events>
<bolt_boltpay_filter_bolt_checkout_javascript>
<observers>
<bolt_boltpay_prepend_variables_postfix_method_call>
<class>Bolt_Custom_Model_Observer</class>
<method>addCustomVariablesAndMethodsToJS</method>
</bolt_boltpay_prepend_variables_postfix_method_call>
</observers>
</bolt_boltpay_filter_bolt_checkout_javascript>
</events>
```
_in the Bolt_Custom_Model_Observer class_
```
/**
* Adds custom javascript to BoltCheckout javascript
*
* @param Varien_Event_Observer …
```

BoltCheckout Javascript filter

---

app/code/community/Bolt/Boltpay/controllers/ShippingController.php

https://app.asana.com/0/544708310157130/1110292802473910
Since we are clearing headers before setting our own headers, we should take the more comprehensive approach and clear headers from both Magento header queues.

comprehensive clearing of headers

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

Bump version to 1.4.0

---

app/code/community/Bolt/Boltpay/Model/BoltOrder.php

https://app.asana.com/0/544708310157130/1110676378336948
We were never taking the email from the session in the admin and always relying on the email to exist as part of a pre-existing customer or previous order from the customer.  New test uncovered the need to support the case for new customer info entered in the admin where the customer had no previous order and did not already exist in the system.  This hotfix covers that case.

Fixes bug for retrieval of email for admin new customer

---

app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
app/code/community/Bolt/Boltpay/controllers/ShippingController.php

https://app.asana.com/0/544708310157130/1110813529071889

correctly adds rules to cache and addresses shipping dependency on coupons

---

app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
tests/unit/testsuite/Bolt/Boltpay/Model/ShippingAndTaxTest.php

https://app.asana.com/0/544708310157130/1111014226785357/f

Expands PO Box Check for more comprehensive identification

---

app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml

https://app.asana.com/0/inbox/544708310157128/1111148925166388/1111146621616741

Enables javascript checks for Product Page orders

---

app/code/community/Bolt/Boltpay/controllers/OrderControllerTrait.php

Fixes bug where back-office orders aren't auto capturing payment.

Fixed bug that was causing admin orders to fail to auto capture.

---

app/code/community/Bolt/Boltpay/Model/Payment.php

Asansa task: https://app.asana.com/0/564264490825835/1111448577711715

Allow invoices to be created for $0.00 orders

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php

It has to be `hints.virtual_terminal_mode`, not `hints.prefill.virtual_terminal_mode`

Fix hints.virtual_terminal_mode flag

---

app/code/community/Bolt/Boltpay/Model/Payment.php

Asana task: https://app.asana.com/0/564264490825835/1115620668332382

Skip void hook notification when clicking on the Magento void button

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

Bump version to 1.4.1

---

app/code/community/Bolt/Boltpay/Model/Payment.php

Asana task: https://app.asana.com/0/564264490825835/1115713860206740

Allow updating order state manually

---

app/code/community/Bolt/Boltpay/Model/Payment.php

Asana task: https://app.asana.com/0/564264490825835/1106472851816631

Voiding after partial capture

---

tests/unit/testsuite/Bolt/Boltpay/controllers/ShippingControllerTest.php

asana task https://app.asana.com/0/941895179897714/1116577852733405/f

 Fix errors in PHPUnit tests when running on local

---

app/code/community/Bolt/Boltpay/controllers/ShippingController.php

https://app.asana.com/0/544708310157130/1117134748905509

Removes address validation for apple pay shipping and tax calculations

---

app/code/community/Bolt/Boltpay/Model/Payment.php

Asana task: https://app.asana.com/0/564264490825835/1115713860206738

Ignore the partial refund fixing mismatch

---

app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
tests/unit/testsuite/Bolt/Boltpay/Model/ShippingAndTaxTest.php

Asana task: https://app.asana.com/0/474713171217346/1118783580900390/f

Fix US region name when it fails to load due to country being switched from non-US to US

---

app/code/community/Bolt/Boltpay/Model/Payment.php

The case: $magentoTotal = "27.9" , $boltTotal = 27.9

Fix the rounding price issue

---

app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
app/code/community/Bolt/Boltpay/Model/BoltOrder.php

These fixes prevent fall the order saving process.
Especially I caught these errors in admin order creation process in one merchant.
The instance based on php5.6 and Magento1.9.4.x

Fix php warnings.

---

app/code/community/Bolt/Boltpay/Model/Payment.php

Asana task: https://app.asana.com/0/564264490825835/1120800506043077

Ingore void hook for unauthorized order

---

app/code/community/Bolt/Boltpay/OrderCreationException.php
tests/unit/testsuite/Bolt/Boltpay/OrderCreationExceptionTest.php

https://app.asana.com/0/544708310157130/1121927273774178

Making highly visible the restricted nature of error codes in order creation

---

app/code/community/Bolt/Boltpay/Model/Observer.php
app/code/community/Bolt/Boltpay/Model/Payment.php
app/code/community/Bolt/Boltpay/etc/config.xml
app/code/community/Bolt/Boltpay/sql/bolt_boltpay_setup/upgrade-1.4.1-1.4.1.1.php
tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php

Asana task: https://app.asana.com/0/564264490825835/803147412595231

Implement temporarily rejected payment API in admin

---

app/code/community/Bolt/Boltpay/Model/Cron.php
app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
app/code/community/Bolt/Boltpay/etc/config.xml
app/code/community/Bolt/Boltpay/sql/bolt_boltpay_setup/upgrade-1.4.1.1-1.4.1.2.php

Asana task: https://app.asana.com/0/564264490825835/1120842637218639

Cleanup unused generated session quotes on PDP

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/Helper/ApiTrait.php
app/code/community/Bolt/Boltpay/Helper/ConfigTrait.php
app/code/community/Bolt/Boltpay/Helper/Data.php
app/code/community/Bolt/Boltpay/Helper/DataDogTrait.php
app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
app/code/community/Bolt/Boltpay/Model/Api2/Order/Rest/Admin/V1.php
app/code/community/Bolt/Boltpay/Model/Coupon.php
app/code/community/Bolt/Boltpay/Model/Observer.php
app/code/community/Bolt/Boltpay/Model/Order.php
app/code/community/Bolt/Boltpay/Model/Order/Detail.php
app/code/community/Bolt/Boltpay/Model/OrderFixer.php
app/code/community/Bolt/Boltpay/Model/Payment.php
app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
app/code/community/Bolt/Boltpay/Model/Service/Order.php
app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
app/code/community/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateController.php
app/code/community/Bolt/Boltpay/controllers/ApiController.php
app/code/community/Bolt/Boltpay/controllers/ConfigurationController.php
app/code/community/Bolt/Boltpay/controllers/OrderController.php
app/code/community/Bolt/Boltpay/controllers/ProductpageController.php
app/code/community/Bolt/Boltpay/controllers/ShippingController.php
lib/Boltpay/DataDog/Autoload.php
lib/Boltpay/DataDog/Client.php
lib/Boltpay/DataDog/Environment.php
lib/Boltpay/DataDog/ErrorTypes.php
lib/Boltpay/DataDog/Request.php
tests/unit/testsuite/Bolt/Boltpay/Helper/DataDogTest.php

New PR per @daisy1754 requested in this PR https://github.com/BoltApp/bolt-magento1/pull/351

 Datadog Integration

---

app/code/community/Bolt/Boltpay/Controller/Traits/OrderControllerTrait.php
app/code/community/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateController.php
app/code/community/Bolt/Boltpay/controllers/OrderController.php

Use M1 convention for auxillary controller classes

mPR07 - Uses M1 standard naming and stucture convention for auxillary controller classes

---

app/code/community/Bolt/Boltpay/controllers/ConfigurationController.php

Update schema configuration check logic to adapt to the new changes in this PR https://github.com/BoltApp/bolt-magento1/pull/354/files#diff-a99dcf1d248ad4259a6ac01123c7807eR41
Asana task: https://app.asana.com/0/564264490825835/1122261460373062

Update schema check logic to look at status instead of state

---

app/code/community/Bolt/Boltpay/Model/Order.php

https://app.asana.com/0/home/544708310157128/1120283062946248
https://app.asana.com/0/home/544708310157128/1120842637218645

Pre-auth order note

---

app/code/community/Bolt/Boltpay/Helper/Data.php
app/code/community/Bolt/Boltpay/Model/Observer.php
app/code/community/Bolt/Boltpay/etc/config.xml

Asana task: https://app.asana.com/0/564264490825835/1117712752858652
This PR adds custom order confirmation page

Keep the cart after placing an order from the product page

---

app/code/community/Bolt/Boltpay/Controller/Traits/WebHookTrait.php
app/code/community/Bolt/Boltpay/controllers/ShippingController.php

Fixes for not checking for hmac from the shipping controller on a prefetch request
https://app.asana.com/0/inbox/544708310157128/1124870062760700/1124869718997648

resolves prefetch hmac problem

---

app/code/community/Bolt/Boltpay/Model/Order.php

Asana task: https://app.asana.com/0/564264490825835/1123239410780665

Associate order to customer when placing on product detail page

---

app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php

Sets up the filters and validation for the hidden extra config values used in 2.0.0
https://app.asana.com/0/home/544708310157128/1123847373963084

mPR.13 - Extra Config values for 2.0.0

---

tests/unit/testsuite/Bolt/Boltpay/CouponHelper.php
tests/unit/testsuite/Bolt/Boltpay/Model/CouponTest.php

Context:
In our test, we create rules that have the side effect of creating coupons.  
Proposal:
When we clean up rules, we also must clean up the created coupons.
https://app.asana.com/0/941895179897714/1124564692070481

Coupon test updates that associates coupon with rule

---

app/code/community/Bolt/Boltpay/Helper/GeneralTrait.php

Asana task: https://app.asana.com/0/564264490825835/1125358293746855

Disallow rendering Bolt button for empty cart

---

app/code/community/Bolt/Boltpay/controllers/ApiController.php

Created in response to:
https://app.asana.com/0/inbox/544708310157128/1125414849391192/1126345327764519
Direct Asana Task:
It appears that the Bolt server can send failed_payment hooks to orders at the wrong time.  Considering that a failed_payment hook is a directive in pre-auth to both cancel and delete the order, this hook should be ignored after an order has been authorized.
https://app.asana.com/0/inbox/544708310157128/1126323016545859/1126345327764519

Adds a check that no payment exist before performing cleanup for failed payment.

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

@mccottry please let me know if you want the changelog to be more verbose.

Bump version to 2.0

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/etc/system.xml
app/design/frontend/base/default/template/boltpay/payment.phtml
app/design/frontend/base/default/template/boltpay/replace.phtml
app/design/frontend/base/default/template/boltpay/replace_firecheckout.phtml
tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php

Adds facility to add JS to pages with the Bolt button via the admin to allow for simpler Frontend integrations
https://app.asana.com/0/544708310157130/1126983787766169

Allows for easy addition of JS on pages with the Bolt Button, permitting simpler integrations

---

README.md
app/code/community/Bolt/Boltpay/Helper/GeneralTrait.php
app/code/community/Bolt/Boltpay/Model/BoltOrder.php
app/code/community/Bolt/Boltpay/Model/Order.php
app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
app/code/community/Bolt/Boltpay/controllers/ShippingController.php

https://app.asana.com/0/544708310157130/1127217232486096

Events used by merchants currently in migration to 2.0.0

---

app/design/frontend/base/default/layout/boltpay.xml

Issue: https://www.screencast.com/t/oh2CuVeCq8
The result after fixing it: https://www.screencast.com/t/is51r89Xh

Update Bolt success page layout

---

.circleci/config.yml

This will introduce better reporting for integration tests step
https://app.asana.com/0/746943642536769/1130800126316371/f

updated integration tests reporter

---

app/code/community/Bolt/Boltpay/controllers/ApiController.php

From Merchant:
_"We have just noticed many orphaned orders in the sales_flat_order table that have null created_at columns and don't exist in our sales order grid and have status of pending_payment and pendin_bolt."_
Explanation:
The problem is that the API format of the failed_payment hook has changed since the start of the pre-auth project.
Initially, it was:
```
{
"quote_id": "6596",
"reference": "GNGR-QHCT-6HDC",
"transaction_id": "TAfb8TSxMYirG",
"notification_type": "failed_payment"
}
```
This format has been updated and is now:
```
{
"id": "TAj2txH5W23Py",
"reference": "RK8G-PZTP-N374",
"order": "218504",
"type": "failed_payment",
"amount": 74900,
"currency": "USD",
"status": "failed",
"display_id": "105130504"
}
```
The formatting changes were not successfully communicated and so …

Use the new failed_payment webhook format to look up orders

---

app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php

The shipping label filter should always be applied
Fixes: https://app.asana.com/0/544708310157130/1132549148365778

Ensures shipping label filter is always applied and honored

---

.circleci/config.yml
tests/scripts/run_phpunit_tests.sh

same as https://github.com/BoltApp/bolt-magento1/pull/471

Add codecov

---

app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
app/code/community/Bolt/Boltpay/controllers/ShippingController.php
app/design/frontend/base/default/template/boltpay/prefetch_shipping_quote.phtml

There are opportunities for errors in our shipping and tax endpoint. Here we cover four potential problems.
1.)  We make sure we include the address data before attempting to save it in the case of 3rd-party address validation via observers
2.)  We clobber exceptions when attempting to create a non-critical address book entry
3.)  We do not call pre-fetch if there is no key for IpStack (when it is disabled)
4.)  We do not cache empty shipping options
Fixes: https://app.asana.com/0/1123603852235561/1130717897778149

Prevents errors in shipping and tax

---

app/code/community/Bolt/Boltpay/Model/Order.php

For create_order performance purposes, we should defer as much of the 3rd-party code as possible for fast returns.
Fixes: https://app.asana.com/0/941895179897714/1135576995166633

Defer third-party order creation process to pending webhook

---

app/code/community/Bolt/Boltpay/Model/BoltOrder.php

Fixes: https://app.asana.com/0/564264490825835/1135529607884618

Update billing address email with shipping address email if it's empty

---

app/code/community/Bolt/Boltpay/Model/Order.php

Update logic to validate quote existence https://screencast.com/t/yHuJyI52q
Fixes: https://app.asana.com/0/564264490825835/1136652844010093

Update logic to validate quote existence

---

app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php

This code should be passing in an exception rather than the exception message.
Fixes: https://app.asana.com/0/564264490825835/1138642577698705

Fixed notifyException parameter bug

---

app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php

Plugin got base price instead of final (changed after advanced pricing, special prices etc)
https://app.asana.com/0/0/1139216972234402/f

fix final price issue for PPC

---

tests/scripts/run_phpunit_tests.sh
tests/unit/testsuite/Bolt/Boltpay/Model/BoltOrderTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php

CI script was broken and swallowed test failure. This PR fixes the script (by adding 'set -e') and skip broken tests for now
https://app.asana.com/0/0/1140078419450593/f
- [x ] Bug fix (change which fixes an issue)
- [x ] Successfully tested on a staging or sandbox server
- [x ] I have performed a self-review of my own code

Fix test script and skip broken tests

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

Bump version to 2.0.2

---

app/code/community/Bolt/Boltpay/Model/Order.php

Previously, we identified that M2 was double removing inventory.  Very similar design and logic exists in M1 and as such, these changes have been implemented to address inventory problems.
Fixes: https://app.asana.com/0/941895179897714/1143967765892403

Addresses inventory issues with failed payment and deferred event execution

---

app/code/community/Bolt/Boltpay/Model/Order.php

Our standing policy has always been to trigger emails after authorization.  This is fairly standard for all payment methods. However, it makes sense to change our policy and prevent the emails from coming if the first hook sent is a irreversible rejection, even though technically, the transaction was authorized.  This implements this exclusion.
Fixes: https://app.asana.com/0/1125081140214268/1143291573116993

Prevents order emails on irrevisibly rejected hooks

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/etc/system.xml

Ability to Restrict Payment Method by Customer Group
Fixes: https://app.asana.com/0/941895179897714/1142266855481737/f

Restrict bolt by customer group

---

.github/CODEOWNERS
.github/pull_request_template.md

Update github documents

---

app/code/community/Bolt/Boltpay/Block/Checkout/Boltpay.php
app/code/community/Bolt/Boltpay/Helper/ApiTrait.php
app/code/community/Bolt/Boltpay/controllers/ConfigurationController.php
lib/Boltpay/Bugsnag/Client.php
lib/Boltpay/Bugsnag/Configuration.php
lib/Boltpay/Bugsnag/Notification.php
lib/Boltpay/DataDog/Client.php
lib/Boltpay/Guzzle/ApiClient.php

Replace curl with guzzle
Fixes: https://app.asana.com/0/564264490825835/1137562463503385

Replace curl with guzzle

---

tests/load/README.md
tests/load/config.js
tests/load/inputs/address.js
tests/load/inputs/amount.js
tests/load/inputs/preauth_cart.js
tests/load/inputs/preauth_payload.js
tests/load/inputs/shipment.js
tests/load/inputs/shippingtax_cart.js
tests/load/inputs/shippingtax_payload.js
tests/load/inputs/test_item.js
tests/load/rpcs/cartdata.js
tests/load/rpcs/create_order.js
tests/load/rpcs/shippingtax.js
tests/load/setup_files/CartDataLoadTest.php
tests/load/setup_files/CartDataLoadTestController.php
tests/load/setup_files/README.md
tests/load/setup_files/setup.sh
tests/load/user_flow.js

These tests will load test the M1 plugin. 
Main tests that we are interested in: 
- Converting cart into Bolt Order
- Shipping and Tax webhook
- Preauth webhook 
We want to make sure that our plugin won't bring down a merchant's store during times of high load. 
Fixes: https://app.asana.com/0/941895179897714/1149771740841855/f
\#changelog
- [ x ] New feature (change which adds functionality)
- [ x ] Successfully tested on a staging or sandbox server
- [ x ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] New and existing unit tests pass …

Loadtests for the M1 plugin

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

Version bump for 2.1.0
Fixes: https://app.asana.com/0/941895179897714/1150510304701558/f

Bump version to 2.1.0

---

tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php

Implements unit test for Bolt_Boltpay_Block_Catalog_Product_Boltpay
Fixes: https://app.asana.com/0/941895179897714/1150161568554697

Unit test: Bolt_Boltpay_Block_Catalog_Product_Boltpay

---

.github/pull_request_template.md

Adds "Test" as a category for type of change
Fixes: https://app.asana.com/0/941895179897714/1150487971365550

Adding category for type of change

---

tests/unit/testsuite/Bolt/Boltpay/Block/FormTest.php

Implements unit tests for Bolt_Boltpay_Block_Form class
Fixes: https://app.asana.com/0/941895179897714/1150161568554699

Implements unit tests for Bolt_Boltpay_Block_Form class

---

tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php

Implements expected exceptions with annotations
Fixes: https://app.asana.com/0/544708310157130/1147324810049189

expectations for exceptions implemented with annotations

---

tests/unit/testsuite/Bolt/Boltpay/CouponHelper.php
tests/unit/testsuite/Bolt/Boltpay/OrderHelper.php
tests/unit/testsuite/Bolt/Boltpay/ProductProvider.php

Many test have failed locally due to improper cleanup.  This addresses the issue.
Fixes: https://app.asana.com/0/544708310157130/1151537717819185

Improves the cleanup of artifacts created from by test

---

tests/unit/testsuite/Bolt/Boltpay/Block/InfoTest.php

Implements unit tests for Bolt_Boltpay_Block_Info class
Fixes: https://app.asana.com/0/941895179897714/1150161568554701

Implements unit tests for Bolt_Boltpay_Block_Info class

---

tests/unit/testsuite/Bolt/Boltpay/OrderHelper.php

Fixed deleting order and create payment
Fixes: https://app.asana.com/0/0/1151503724856645/f
- [ +] Bug fix (change which fixes an issue)

Fix Unit test deleting order and create payment

---

.circleci/config.yml

This PR notifies on the #mx-greenkeeper channel on slack when things fail on master.
#changelog

[Greenkeeper] Notify slack if build fails

---

tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
tests/unit/testsuite/Bolt/Boltpay/Controller/Traits/OrderControllerTraitTest.php

Unit test for class Bolt_Boltpay_Controller_Traits_OrderControllerTrait
Fixes: https://app.asana.com/0/941895179897714/1152215733866363

Unit test for class Bolt_Boltpay_Controller_Traits_OrderControllerTrait

---

app/code/community/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateController.php
tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
tests/unit/testsuite/Bolt/Boltpay/Controller/Traits/OrderControllerTraitTest.php
tests/unit/testsuite/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateControllerTest.php

Revision of PR #574  to meet new M1 test standard
Fixes: https://app.asana.com/0/941895179897714/1152215733866363

Revision of PR to meet new M1 test standard

---

tests/load/README.md
tests/load/config.js
tests/load/user_flow.js

- Add SLEEP environment variable in load test scripts so that we simulate tests that will test loads of less than a user per second (i.e 1 user every 5 seconds)
- Add BLACKFIRE_HEADER environment variable so that we can create a profile of the execution path of the requests using BlackFire
Fixes: https://app.asana.com/0/941895179897714/1154453239292857/f
\#changelog

Add env vars load test

---

app/code/community/Bolt/Boltpay/Model/Payment.php
tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php

We use Magento's order cancel method to return stock to the inventory. However, internally, Magento will silently skip this under certain conditions, including when an order is under payment review. Since we now define irreversibly and reversibly rejected hooks as payments under review, we can not directly cancel them from this state. Therefore, we temporarily switch these orders to pending payment and cancel them from there in order to properly return stock.
Fixes: https://app.asana.com/0/1125081140214268/1154516342720281
#changelog Bugfix: Stock returned for canceled Bolt rejected orders

Restore inventory on canceled payment review orders

---

tests/unit/testsuite/Bolt/Boltpay/Helper/GeneralTraitTest.php

Unit Test: Bolt_Boltpay_Helper_GeneralTrait
Fixes: https://app.asana.com/0/941895179897714/1152215733866375

Unit Test: Bolt_Boltpay_Helper_GeneralTrait

---

tests/unit/testsuite/Bolt/Boltpay/ConfigProxy.php
tests/unit/testsuite/Bolt/Boltpay/InvalidTransitionExceptionTest.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

Implements Unit Test for Bolt_Boltpay_InvalidTransitionException
Fixes: https://app.asana.com/0/941895179897714/1155482281891288
\#changelog

Unit Test: Bolt_Boltpay_InvalidTransitionException

---

tests/unit/testsuite/Bolt/Boltpay/ConfigProxy.php
tests/unit/testsuite/Bolt/Boltpay/Helper/UrlTraitTest.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

Unit Test: Bolt_Boltpay_Helper_UrlTrait
Fixes: https://app.asana.com/0/941895179897714/1155424674859521
\#changelog

Unit Test: Bolt_Boltpay_Helper_UrlTrait

---

tests/unit/testsuite/Bolt/Boltpay/ConfigProxy.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

Unit Test: Bolt_Boltpay_Model_Order_Detail
Fixes: https://app.asana.com/0/941895179897714/1155424674859530
\#changelog

Unit Test: Bolt_Boltpay_Model_Order_Detail

---

tests/unit/testsuite/Bolt/Boltpay/ConfigProxy.php
tests/unit/testsuite/Bolt/Boltpay/Model/Productpage/CartTest.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

Unit Test: Bolt_Boltpay_Model_Productpage_Cart
Fixes: https://app.asana.com/0/941895179897714/1155433851047433
\#changelog

Unit Test: Bolt_Boltpay_Model_Productpage_Cart

---

tests/unit/testsuite/Bolt/Boltpay/ConfigProxy.php
tests/unit/testsuite/Bolt/Boltpay/Model/Service/OrderTest.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

Unit Test: Bolt_Boltpay_Model_Service_Order
Fixes: https://app.asana.com/0/941895179897714/1155433851047440
\#changelog

Unit Test: Bolt_Boltpay_Model_Service_Order

---

tests/unit/testsuite/Bolt/Boltpay/ConfigProxy.php
tests/unit/testsuite/Bolt/Boltpay/Model/Source/ThemesTest.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

Unit Test: Bolt_Boltpay_Model_Source_Themes
Fixes: https://app.asana.com/0/941895179897714/1155433851047447
\#changelog

Unit Test: Bolt_Boltpay_Model_Source_Themes

---

tests/unit/testsuite/Bolt/Boltpay/ConfigProxy.php
tests/unit/testsuite/Bolt/Boltpay/Model/StatsTest.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

Unit Test: Bolt_Boltpay_Model_Stats
Fixes: https://app.asana.com/0/941895179897714/1155468754820216
\#changelog

Unit Test: Bolt_Boltpay_Model_Stats

---

app/code/community/Bolt/Boltpay/Block/Form.php
app/code/community/Bolt/Boltpay/BoltGlobalTrait.php

These comments still describe legacy behavior and should be updated to reflect the present.
Fixes: https://app.asana.com/0/941895179897714/1155614141086433

Updates comments to reflect present use

---

tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php

Shortens method names for PR #614 
Fixes: https://app.asana.com/0/1131034199022699/1157340557191681

effort shortening method names: Unit Test for Bolt_Boltpay_Block_Checkout_BoltpayTest

---

tests/unit/testsuite/Bolt/Boltpay/Helper/TransactionTraitTest.php

Unit Test: Bolt_Boltpay_Helper_TransactionTrait
Fixes: https://app.asana.com/0/941895179897714/1155292421961832
\#changelog

Unit Test: Bolt_Boltpay_Helper_TransactionTrait

---

tests/unit/testsuite/Bolt/Boltpay/Helper/LoggerTraitTest.php

Unit Test: Bolt_Boltpay_Helper_LoggerTrait
Fixes: https://app.asana.com/0/941895179897714/1155292421961830
\#changelog

Unit Test: Bolt_Boltpay_Helper_LoggerTrait

---

app/code/community/Bolt/Boltpay/controllers/ApiController.php
tests/unit/testsuite/Bolt/Boltpay/controllers/ApiControllerTest.php

Handles notice displayed in developer mode for transactions.  This bug and fix does not affect production and is being applied for testing and dev environments.
Fixes: https://app.asana.com/0/941895179897714/1157028338214625

Handles notice displayed about $transaction in developer mode for pending hooks

---

app/code/community/Bolt/Boltpay/Model/Cron.php
app/code/community/Bolt/Boltpay/etc/config.xml
tests/unit/testsuite/Bolt/Boltpay/Model/CronTest.php

Create a Cron job to deactivate quotes which belong to created orders
Ansa tasks:
https://app.asana.com/0/564264490825835/1156439433189898
https://app.asana.com/0/564264490825835/1158170256220522
https://app.asana.com/0/1145651657031066/1149651386853174

Create a Cron job to deactivate quotes which belong to created orders

---

app/code/community/Bolt/Boltpay/Model/Order.php
tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php

Orders are being blocked because Bolt has a record transaction for an order reference. Somehow, plugins are reactivating the session quote order reference. Because once the transaction is processed and confirmed in Magento as an authorized order the session quote becomes redundant, it can safely be remove, effectively eliminating any opportunity for reuse of it's ID as an order reference. For posterity, we preserve the immutable quote and associate it with the order after all order creation events have been executed.
Note: I see nothing wrong with having this in addition to a defensively coded cron job running as a failure recovery measure and I move that we adopt this along side of PR #613 
Fixes: https://app.asana.com/0/564264490825835/1156439433189898
(Optional: Add a changelog by …

The division already has a successful payment - preemptive resolution

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

Version bump 2.2.0
Fixes: https://app.asana.com/0/436430054069245/1150510304701558/f

Bump v2.2.0

---

app/code/community/Bolt/Boltpay/Helper/ApiTrait.php
tests/unit/testsuite/Bolt/Boltpay/Helper/ApiTraitTest.php

Fixes: https://app.asana.com/0/1131034199022699/1157340263780225/f
\#changelog

Unit Test:  Helper/ApiTraitTest

---

tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php

**THIS PR SHOULD BE MERGED TO MASTER ONLY AFTER PR #622 and #623 .  Base branch must be switched**
Updates existing Bolt_Boltpay_Model_Order test. This PR is broken down into 3 smaller PR's per @matt-thomason 's suggestion.
Fixes: https://app.asana.com/0/1131034199022699/1157340557191693

Updates existing Bolt_Boltpay_Model_Order test. PR 3 or 3

---

tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php

**THIS PR SHOULD BE MERGED TO MASTER ONLY AFTER PR #622.  Base branch must be switched**
Updates existing Bolt_Boltpay_Model_Order test. This PR is broken down in to 3 smaller PR's per @matt-thomason 's suggestion.
Fixes: https://app.asana.com/0/1131034199022699/1157340557191693

Updates existing Bolt_Boltpay_Model_Order test. PR 2 or 3

---

app/code/community/Bolt/Boltpay/Model/Order.php
tests/unit/testsuite/Bolt/Boltpay/MockingTrait.php
tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php

Updates existing Bolt_Boltpay_Model_Order test.  This PR is broken down in to 3 smaller PR's per @matt-thomason 's suggestion.
Fixes: https://app.asana.com/0/1131034199022699/1157340557191693

Updates existing Bolt_Boltpay_Model_Order test.  PR 1 of 3

---

app/code/community/Bolt/Boltpay/Model/Admin/ExtraConfig.php
app/code/community/Bolt/Boltpay/Model/Order.php
app/code/community/Bolt/Boltpay/controllers/ApiController.php
tests/unit/testsuite/Bolt/Boltpay/Model/Admin/ExtraConfigTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php
tests/unit/testsuite/Bolt/Boltpay/controllers/ApiControllerTest.php

Prevents processing on non-Bolt orders or orders in unexpected states
Fixes: https://app.asana.com/0/1125081140214268/1152717957166833/f
https://app.asana.com/0/1125081140214268/1155208530958525

Prevent processing on non-Bolt orders or orders in unexpected states

---

app/code/community/Bolt/Boltpay/Model/Order.php
tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php

This PR resolves the following case and allow the virtual order to be created:
1. The customer adds a virtual product to cart
2. Sometimes, the create_order hook is sent to Magento with the body that doesn’t have the shipments property. Here is the Datadog link: https://app.datadoghq.com/logs?cols=core_host%2Ccore_service&event=AQAAAXAatLto2ziKdwAAAABBWEFhdFR6MVRVQmRlOFhGb2UxMw&from_ts=1580995800000&index=main&live=false&messageDisplay=inline&query=%22145000253%7C1532%22&stream_sort=asc&to_ts=1580996400000
3. Then it throws exception “Notice: Undefined property: stdClass::$shipments “. Here is the Bugsnag link: https://app.bugsnag.com/bolt/magento/errors/5dc00143c0b9d00019c23b37?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[search][0][type]=eq&filters[search][ …

Fix exception 'Undefined property: stdClass::shipments'

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

Add changelog for 2.3.0 release.

---

README.md
app/code/community/Bolt/Boltpay/Model/Payment.php

Event bolt_boltpay_capture_before: Execute before capturing payment
Fixes: 
https://app.asana.com/0/564264490825835/1161099143858659
https://app.asana.com/0/564264490825835/1161569416447553

Event bolt_boltpay_capture_before

---

app/code/community/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateController.php
tests/unit/testsuite/Bolt/Boltpay/controllers/Adminhtml/Sales/Order/CreateControllerTest.php

Complete Unit Test: Bolt_Boltpay_Adminhtml_Sales_Order_CreateController
Fixes: https://app.asana.com/0/1131034199022699/1157340263780243

Complete Unit Test: Bolt_Boltpay_Adminhtml_Sales_Order_CreateController

---

tests/unit/testsuite/Bolt/Boltpay/controllers/ApiControllerTest.php

Complete unit test: Bolt_Boltpay_ApiController
Fixes: https://app.asana.com/0/1131034199022699/921469870263920

Complete unit test: Bolt_Boltpay_ApiController

---

app/code/community/Bolt/Boltpay/Model/Order.php
tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php

Checking for out of stock had lower precedence then checking for saleable.  Since products marked out of stock can be automatically marked as not saleable, the out of stock message was being suppressed.
Fixes: https://app.asana.com/0/941895179897714/1161595777971329

Check for out-of-stock before saleable

---

app/code/community/Bolt/Boltpay/Model/BoltOrder.php
tests/unit/testsuite/Bolt/Boltpay/Model/BoltOrderTest.php

Remove virtual quote shipping address data before sendding to Bolt
Fixes: https://app.asana.com/0/564264490825835/1161595777971337

Remove virtual quote shipping address data before sendding to Bolt

---

.github/stale.yml

[Stale] Close stale PRs

---

app/code/community/Bolt/Boltpay/Model/BoltOrder.php
tests/unit/testsuite/Bolt/Boltpay/Model/BoltOrderTest.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

Update Unit Test class to reach 100% code coverage for the model
Fixes: https://app.asana.com/0/1131034199022699/1157340557191685

Complete unit test: Bolt_Boltpay_Model_BoltOrder

---

app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
tests/unit/testsuite/Bolt/Boltpay/Model/ShippingAndTaxTest.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

Complete unit test: Bolt_Boltpay_Model_ShippingAndTax
Fixes: https://app.asana.com/0/1131034199022699/1157340557191703

Complete unit test: Bolt_Boltpay_Model_ShippingAndTax

---

tests/unit/testsuite/Bolt/Boltpay/TestHelper.php
tests/unit/testsuite/Bolt/Boltpay/controllers/ShippingControllerTest.php

Complete unit test: Bolt_Boltpay_ShippingController
Fixes: https://app.asana.com/0/1131034199022699/1162661892412283

Complete unit test: Bolt_Boltpay_ShippingController

---

README.md

People are having issues running unit test locally.  This update to the README.md should help
Fixes: 
https://boltpay.slack.com/archives/CKBBANKD2/p1582500506001700
https://boltpay.slack.com/archives/CKBBANKD2/p1582554286005200
https://boltpay.slack.com/archives/CKBBANKD2/p1582557359009200
\#changelog

Unit test updates to help people who run test locally

---

app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
app/code/community/Bolt/Boltpay/Helper/Data.php
app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php
tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/Productpage/CartTest.php

Add suport for custom options on PPC
Fixes: https://app.asana.com/0/941895179897714/1161793187073239
#changelog Add suport for custom options on PPC

Add support for configurable products on PPC

---

app/code/community/Bolt/Boltpay/Helper/ConfigTrait.php

small comment refinement

---

app/code/community/Bolt/Boltpay/Model/Payment.php
tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php

Update Unit Test class to reach complete code coverage for the model
Fixes: https://app.asana.com/0/1131034199022699/1157340557191697

Complete unit test: Bolt_Boltpay_Model_Payment

---

app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php

Virtual Product
Although virtual products are not physical in nature, they do represent something that can be sold, such as a membership, service, warranty, or subscription. Virtual products can be sold individually, or included as part of the following product types:
Grouped Product
Bundle Product
source: https://docs.magento.com/m1/ce/user_guide/catalog/product-virtual.html
Fixes: https://app.asana.com/0/941895179897714/1165040796588156
#changelog Product Page Checkout - Adds Virtual Product support.

Product Page Checkout - Adds Virtual Product support

---

tests/unit/testsuite/Bolt/Boltpay/Model/ObserverTest.php

Make ObserverTest conform to our unit test standards and general clean up
#changelog Clean up ObserverTest
#mergeWhenGreen

Clean up observer test

---

app/code/community/Bolt/Boltpay/Model/Cron.php
tests/unit/phpunit.xml
tests/unit/testsuite/Bolt/Boltpay/Model/CronTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php

Add unit tests for cron and order
#changelog Add unit tests for cron and order

[M1P-14] Add unit tests for cron and order

---

.circleci/config.yml

Re-enabled disabled integration tests.
Fixes: https://app.asana.com/0/941895179897714/1152119232273305/f
#changelog Re-enable integration tests on master.

Re-enabled integration test

---

.circleci/config.yml

Reverts BoltApp/bolt-magento1#674
Too optimistic :(
#changelog Reverts PR#674 integration test

Revert "Re-enabled integration test"

---

app/code/community/Bolt/Boltpay/Controller/Traits/WebHookTrait.php
app/code/community/Bolt/Boltpay/Helper/ApiTrait.php
app/code/community/Bolt/Boltpay/Helper/BugsnagTrait.php
app/code/community/Bolt/Boltpay/Helper/Data.php
app/code/community/Bolt/Boltpay/Helper/LoggerTrait.php
tests/unit/phpunit.xml
tests/unit/testsuite/Bolt/Boltpay/Controller/Traits/WebHookTraitTest.php
tests/unit/testsuite/Bolt/Boltpay/Helper/ApiTraitTest.php
tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php

Finish helper testing and some formatting
#changelog Finish helper testing and some formatting

[M1P-13] Finish helper testing

---

app/code/community/Bolt/Boltpay/Model/Coupon.php
tests/unit/testsuite/Bolt/Boltpay/CouponHelper.php
tests/unit/testsuite/Bolt/Boltpay/Model/CouponTest.php

Update Unit Test class to reach 100% code coverage for the model
Fixes: https://app.asana.com/0/1131034199022699/1157340557191687
#changelog Complete unit test: Bolt_Boltpay_Model_Coupon

Complete unit test: Bolt_Boltpay_Model_Coupon

---

app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
app/code/community/Bolt/Boltpay/Model/Productpage/Cart.php
app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/Productpage/CartTest.php

Adds support for grouped products in PPC
Fixes: https://app.asana.com/0/941895179897714/1165040796588158
#changelog Product Page Checkout - Adds Grouped Product support

PPC Grouped Product Support

---

app/code/community/Bolt/Boltpay/Model/Observer.php
tests/unit/testsuite/Bolt/Boltpay/Model/ObserverTest.php

WIP pending some polishing changes
Complete unit test: Bolt_Boltpay_Model_Observer
Fixes: https://app.asana.com/0/1131034199022699/1157340557191691
#changelog Complete unit test: Bolt_Boltpay_Model_Observer

Complete unit test: Bolt_Boltpay_Model_Observer

---

app/code/community/Bolt/Boltpay/Model/Order.php
tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php

Add one last test, cleaned up the comments a bit, and reordered some tests
[M1P-16]
#changelog Add one last test

[M1P-16] Add one last test

---

app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php

Add support for Bundle product type on Product Page Checkout
Fixes: https://app.asana.com/0/941895179897714/1165040796588162
#changelog Product Page Checkout - Adds Bundle Product support

PPC Bundle Product Support

---

.circleci/config.yml

Fix circleci config typo
#changelog Fix CircleCI config typo

Fix CircleCI config typo

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

Bump version to 2.4.0
#changelog Bump version to 2.4.0

Bump version to 2.4.0

---

app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml

There was no validation on quantity. Throw an error on zero quantity.
Fixes: https://app.asana.com/0/941895179897714/1166410238431249
#changelog Error on zero quantity

Error on zero quantity

---

app/code/community/Bolt/Boltpay/controllers/ApiController.php

Testing revealed that we are unable to apply discount via bolt modal with dev mode turned on
Fixes: https://app.asana.com/0/inbox/544708310157128/1166427612234707/1166448661193411
#changelog Resolves developer mode error on Applying discounts from modal

Resolves developer mode error on Applying discounts from modal

---

app/code/community/Bolt/Boltpay/Helper/Data.php
app/code/community/Bolt/Boltpay/Model/Observer.php
app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
tests/unit/testsuite/Bolt/Boltpay/Helper/DataTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/ObserverTest.php

Add support for Bundle product type on Product Page Checkout
Fixes: https://app.asana.com/0/941895179897714/1165040796588162
#changelog Product Page Checkout - Adds Bundle Product support

Product Page Checkout - Adds Bundle Product support

---

CHANGELOG.md

Update changelog
#changelog Update changelog for rc2

Update changelog for rc2

---

app/code/community/Bolt/Boltpay/Model/Cron.php
app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
app/code/community/Bolt/Boltpay/controllers/ShippingController.php
tests/unit/testsuite/Bolt/Boltpay/Model/CronTest.php

Removed an unused method that was ignored by code coverage. Also rewrote a line in ShippingController because it was never executed before since exitImmediately defaults to true. Also added the missing test for cron.
#changelog 100% code coverage

100% code coverage

---

app/code/community/Bolt/Boltpay/Helper/GeneralTrait.php
app/code/community/Bolt/Boltpay/Model/FeatureSwitch.php
tests/unit/testsuite/Bolt/Boltpay/Helper/GeneralTraitTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/FeatureSwitchTest.php

Fixes: https://app.asana.com/0/1163213880723410/1163214272935461/f
#changelog Write Lib to use feature switches anywhere in M1 plugin

Write Lib to use feature switches anywhere in M1 plugin

---

app/code/community/Bolt/Boltpay/Model/FeatureSwitch.php
app/code/community/Bolt/Boltpay/controllers/FeatureswitchesController.php
tests/unit/testsuite/Bolt/Boltpay/controllers/FeatureswitchesControllerTest.php

Fixes: https://app.asana.com/0/1163213880723410/1163214273078115/f
#changelog Create webhook which if hit will fetch the latest feature switches from Bolt

Create webhook which if hit will fetch the latest feature switches from Bolt

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

#changelog Bump version to 2.4.1

Bump version to 2.4.1

---

app/code/community/Bolt/Boltpay/Model/Coupon.php
app/code/community/Bolt/Boltpay/controllers/ApiController.php

Fixes: https://app.asana.com/0/941895179897714/1166427612234707
#changelog Fix can't apply discount in developer mode

[M1P-25] Fix can't apply discount in developer mode

---

app/code/community/Bolt/Boltpay/Helper/ConfigTrait.php
app/code/community/Bolt/Boltpay/Helper/GeneralTrait.php
app/code/community/Bolt/Boltpay/Model/FeatureSwitch.php
tests/unit/testsuite/Bolt/Boltpay/Helper/ConfigTraitTest.php
tests/unit/testsuite/Bolt/Boltpay/Helper/GeneralTraitTest.php

Simple implementation of the Bolt Enabled Feature Switch
Fixes: https://app.asana.com/0/1163213880723410/1167055882060433
#changelog Bolt Enabled Feature Switch Implementation

Bolt Enabled Feature Switch Implementation

---

.circleci/config.yml
.circleci/scripts/rc-tag.sh

As described. M1 implementation of: https://github.com/BoltApp/bolt-magento2/pull/591
#changelog Add rc autotagger

Add rc autotagger

---

.github/CODEOWNERS

Add roopak as codeowner for circle stuff
#changelog Add roopak as codeowner for circle stuff

Add roopak as codeowner for circle stuff

---

.github/CODEOWNERS

Don't think my previous change worked. Apparently the order determines the precedence...
#changelog Fix precedence in codeowners

Fix precedence in codeowners

---

app/code/community/Bolt/Boltpay/Helper/GraphQLTrait.php
app/code/community/Bolt/Boltpay/Model/FeatureSwitch.php
app/code/community/Bolt/Boltpay/Model/Observer.php
app/code/community/Bolt/Boltpay/controllers/FeatureswitchesController.php
app/code/community/Bolt/Boltpay/etc/system.xml
tests/unit/autoload.php
tests/unit/testsuite/Bolt/Boltpay/Helper/GraphQLTraitTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/FeatureSwitchTest.php
tests/unit/testsuite/Bolt/Boltpay/TestHelper.php
tests/unit/testsuite/Bolt/Boltpay/controllers/FeatureswitchesControllerTest.php

Update Feature Switches on API Key change
Fixes: https://app.asana.com/0/941895179897714/1167274698134548
#changelog Update Feature Switches on API Key change

Update Feature Switches on API Key change

---

app/code/community/Bolt/Boltpay/Model/Admin/ApiKey.php
tests/unit/testsuite/Bolt/Boltpay/Model/Admin/ApiKeyTest.php

Add missing updates for PR #724 
Thanks @adentong for making me aware to this.  The original overwritten -PR #732
Fixes: https://app.asana.com/0/941895179897714/1167274698134548
#changelog Adds missing boltpay/admin_apiKey model

Updates outdated boltpay/admin_apiKey model with improved test

---

app/code/community/Bolt/Boltpay/Block/Adminhtml/System/Config/Form/Button.php
app/code/community/Bolt/Boltpay/controllers/ConfigurationController.php
app/code/community/Bolt/Boltpay/etc/config.xml
app/code/community/Bolt/Boltpay/etc/system.xml
app/design/adminhtml/default/default/template/boltpay/system/config/button.phtml

See https://github.com/BoltApp/bolt-magento1/pull/492.
#changelog Update the strings for Bolt's admin configuration and reorder and group them

[M1P-5] Update admin configs

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

#changelog Bump version to 2.5.0

Bump version to 2.5.0

---

app/code/community/Bolt/Boltpay/Helper/ConfigTrait.php

Refactor Code by using the conditional operator "?:"
Fixes: https://app.asana.com/0/564264490825835/1169865286823289
#changelog Refactor Code by using the conditional operator ?:

Refactor Code by using the conditional operator ?:

---

tests/unit/testsuite/Bolt/Boltpay/Model/CouponTest.php

This fixes the test that was failing for circle ci
Fixes: https://boltpay.atlassian.net/browse/M1P-40
#changelog [M1P-40] Resolve issue causing coverage to be below 100%

[M1P-40] Resolve issue causing coverage to be below 100%

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

Production readiness:
https://boltpay.atlassian.net/browse/M1P-47
#changelog Bump version to 2.6.0

Bump version to 2.6.0

---

.circleci/config.yml

Before this PR we use custom branch of integration-test repo because integration-test repo had issue with M1 test. Now that it's fixed, we can simply use the master branch
#changelog Use master branch for integration test

Use master branch for integration test

---

.circleci/config.yml

#changelog Try to fix autotagger not tagging second person

Try to fix autotagger not tagging second person

---

.github/CODEOWNERS
.github/pull_request_template.md

#changelog Add Vitaliy as code owner

Add Vitaliy as code owner

---

app/code/community/Bolt/Boltpay/Controller/Traits/WebHookTrait.php
tests/unit/testsuite/Bolt/Boltpay/Controller/Traits/WebHookTraitTest.php

Each webhook request (even shipping and tax) creates new session entry. For sessions stored in filesystem this equals to adding 1kb file for each webhook request. This PR destroys session after each signed webhook is complete. Only signed webhooks are chosen to be sure we delete only actions that are initiated by Bolt, both present and future.
Tested locally with session saving configured to filesystem, database and redis
Fixes: https://boltpay.atlassian.net/browse/M1P-51
#changelog Destroy session after webhook

Destroy session after webhook

---

app/code/community/Bolt/Boltpay/Block/Catalog/Product/Boltpay.php
app/design/frontend/base/default/template/boltpay/catalog/product/configure_checkout.phtml
tests/unit/testsuite/Bolt/Boltpay/Block/Catalog/Product/BoltpayTest.php

Frontend configurable product validation was deferred in initial implementation.  This completes it.
Fixes: https://boltpay.atlassian.net/browse/M1P-53
#changelog Implement frontend stock validation for configurable products in PPC

Implement frontend stock validation for configurable products in PPC

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

#changelog Bump to version 2.7.0

Bump to version 2.7.0

---

.circleci/config.yml
.circleci/scripts/tag-rc-if-necessary.sh

Fixes: [MX-1104]
#changelog Update autotagger schedule
[MX-1104]: https://boltpay.atlassian.net/browse/MX-1104

Update autotagger schedule

---

app/code/community/Bolt/Boltpay/Model/Order.php
tests/unit/testsuite/Bolt/Boltpay/Model/OrderTest.php

Fixes: https://boltpay.atlassian.net/browse/M1P-60
#changelog Fix exception:  Call to a member function getMethod() on boolean

Fix exception:  Call to a member function getMethod() on boolean

---

app/code/community/Bolt/Boltpay/Model/FeatureSwitch.php
app/code/community/Bolt/Boltpay/Model/Updater.php
tests/unit/testsuite/Bolt/Boltpay/Model/FeatureSwitchTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/UpdaterTest.php

Updating the Bolt plugin on merchant sites has generally been handled by contractors via merchant experience, integration engineers, or merchant self-upgrades, usually initiated by request of either support or customer success managers in response to production problems. This is not ideal.
This allows update requests to be triggered automatically upon any major, minor, or patch version updates. Available update is detected by comparing installed version to the latest on Magento Marketplace (retrieved via Magento Connect). Alternatively, activating M1_BOLT_UPDATE_USE_GIT feature switch will instead use latest Github release for comparison.
Update check happens in admin area, after login. If an update is available:
1. Display custom BoltPopup on first page after admin detailing steps needed …

Version Update Admin Notification: Updater (Business Logic/Model Class) [M1P-56]

---

modman

#changelog Added missing entry to modman definition.

Added missing entry to modman definition.

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

Fixes: (link Jira Task)
#changelog Update version to 2.8.0

Update version to 2.8.0

---

.circleci/config.yml

Since we stopped working on M1 I'm going to manually tag only when there have been new commits.
Fixes: (link Jira Task)
#changelog Remove tagger

Remove tagger

---

app/code/community/Bolt/Boltpay/Block/Info.php
app/code/community/Bolt/Boltpay/Model/Payment.php
app/code/community/Bolt/Boltpay/etc/config.xml
tests/unit/testsuite/Bolt/Boltpay/Block/InfoTest.php
tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php

Proposed changes to PR #777
Fixes: https://boltpay.atlassian.net/browse/M1P-67
#changelog Ning display apm proposed changes

Ning display apm proposed changes

---

.circleci/config.yml

Change Pavel to primary slack notification for autotagger
#changelog Change Pavel to primary slack notification for autotagger

Change Pavel to primary slack notification for autotagger

---

app/code/community/Bolt/Boltpay/Model/Payment.php
tests/unit/testsuite/Bolt/Boltpay/Model/PaymentTest.php

Support multi-store environment when calling transmit
Fixes: 
https://boltpay.atlassian.net/browse/M2P-142
https://boltpay.atlassian.net/browse/EN-367
#changelog Support multi-store environment when calling transmit

Support multi-store environment when calling transmit

---

app/code/community/Bolt/Boltpay/Model/Order.php
app/code/community/Bolt/Boltpay/Model/ShippingAndTax.php
app/code/community/Bolt/Boltpay/controllers/ApiController.php
lib/Boltpay/GuzzleHttp/Exception/RequestException.php
lib/Boltpay/GuzzleHttp/Handler/CurlFactory.php
tests/unit/testsuite/Bolt/Boltpay/Model/ShippingAndTaxTest.php

**WIP until actually tested in the PHP 5.4 context**
This changes code to be compatible with PHP 5.4 as we advertise that we support it
Fixes: https://boltpay.slack.com/archives/CKBBANKD2/p1594637919044000
#changelog Compatibility changes for PHP 5.4

Compatibility changes for PHP 5.4

---

app/code/community/Bolt/Boltpay/Model/Updater.php

Fix unit test failure: Array () does not match expected type boolean
See here: See https://app.circleci.com/pipelines/github/BoltApp/bolt-magento1/1055/workflows/3c9c87c3-12d0-4b7f-b9de-26e218d3c7df/jobs/12506
Fixes: https://boltpay.atlassian.net/browse/M1P-69
#changelog Fix unit test failure: Array () does not match expected type boolean

M1P-69 Fix unit test failure: Array () does not match expected type boolean

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

#changelog Version bump for 2.9.0

Version bump for 2.9.0

---

app/code/community/Bolt/Boltpay/Helper/UrlTrait.php
app/code/community/Bolt/Boltpay/etc/system.xml
tests/unit/testsuite/Bolt/Boltpay/Block/Checkout/BoltpayTest.php
tests/unit/testsuite/Bolt/Boltpay/Helper/ApiTraitTest.php
tests/unit/testsuite/Bolt/Boltpay/Helper/UrlTraitTest.php

Fixes: (link Jira Task)
#changelog Support staging and local URLs

Support staging and local URLs

---

CHANGELOG.md
app/code/community/Bolt/Boltpay/etc/config.xml

Fixes: (link Jira Task)
#changelog Version bump for 2.10.0

Version bump for 2.10.0

---

app/code/community/Bolt/Boltpay/Model/BoltOrder.php

Sometimes, we need to send the item type of DIGITAL to Bolt even when the product type is not Virtual. This PR is to add a filter event to allow us to alter the product type if needed.
Fixes: https://boltpay.atlassian.net/browse/M1P-90
#changelog Add filter event for the product type

Add filter event for the product type
